export type ResourceType = {
  url: string;
  resource: string;
  title: string | null;
  description: string;
  icon: string;
  category: string;
};

export const resourcesList: ResourceType[] = [
  {
    url: "https://my.university.innopolis.ru/",
    resource: "My University",
    title: null,
    description:
      "Request references, find out your grades, scholarship, fill the forms for internships.",
    icon: "icon-[ic--baseline-school]",
    category: "Academic",
  },
  {
    url: "https://my.university.innopolis.ru/profile/personal-form/index?tab=validations",
    resource: "My University",
    title: "Gradebook",
    description: "View your marks for all previous semesters.",
    icon: "icon-[material-symbols--assignment-outline]",
    category: "Academic",
  },
  {
    url: "https://my.university.innopolis.ru/profile/edu-certs/create",
    resource: "My University",
    title: "Request references",
    description: "Request a reference about studying or other things.",
    icon: "icon-[material-symbols--description-outline]",
    category: "Academic",
  },
  {
    url: "https://my.university.innopolis.ru/profile/personal-form/index?tab=scholarship",
    resource: "My University",
    title: "Scholarship",
    description:
      "See how the scholarship is calculated for your current semester in My University.",
    icon: "icon-[material-symbols--credit-card-outline]",
    category: "Financial",
  },
  {
    url: "https://my.university.innopolis.ru/profile/applications",
    resource: "My University",
    title: "Templates of applications",
    description:
      "Access and download templates for various university applications.",
    icon: "icon-[material-symbols--article-outline]",
    category: "Academic",
  },
  {
    url: "https://innohassle.ru/scholarship",
    resource: "InNoHassle",
    title: "Scholarship calculator",
    description:
      "Calculate your expected scholarship for the next semester in InNoHassle.",
    icon: "icon-[material-symbols--calculate-outline]",
    category: "Financial",
  },
  {
    url: "https://psychologist.innopolis.university/appointment/new",
    resource: "Psychologist",
    title: null,
    description:
      "Book an appointment with a psychologist by using this service.",
    icon: "icon-[material-symbols--psychology-outline]",
    category: "Support",
  },
  {
    url: "https://eduwiki.innopolis.university/index.php/Main_Page",
    resource: "Eduwiki",
    title: null,
    description: "View the official documents from DoE.",
    icon: "icon-[material-symbols--library-books-outline]",
    category: "Academic",
  },
  {
    url: "https://eduwiki.innopolis.university/index.php/AcademicCalendar",
    resource: "Eduwiki",
    title: "Academic calendar",
    description:
      "View the official academic calendar with holidays and study days.",
    icon: "icon-[material-symbols--calendar-month-outline]",
    category: "Academic",
  },
  {
    url: "https://eduwiki.innopolis.university/index.php/ALL:StudyPlan",
    resource: "Eduwiki",
    title: "Study plan",
    description:
      "View the study plan with a documented amount of required studying hours.",
    icon: "icon-[material-symbols--book-outline]",
    category: "Academic",
  },
  {
    url: "https://eduwiki.innopolis.university/index.php/All:Schedule",
    resource: "Eduwiki",
    title: "Schedule",
    description: "View the official schedule of classes.",
    icon: "icon-[material-symbols--schedule-outline]",
    category: "Academic",
  },
  {
    url: "https://innohassle.ru/schedule",
    resource: "InNoHassle",
    title: "Schedule",
    description: "Conveniently view your schedule in the calendar.",
    icon: "icon-[material-symbols--today-outline]",
    category: "Academic",
  },
  {
    url: "https://my.innopolis.university/event",
    resource: "New My University",
    title: "Events for innopoints",
    description: "Earn innopoints by participating in projects and activities.",
    icon: "icon-[material-symbols--currency-ruble-rounded]",
    category: "Extracurricular",
  },
  {
    url: "https://my.innopolis.university/store",
    resource: "New My University",
    title: "InnoStore",
    description:
      "Redeem your innopoints for cool merch and rewards at the InnoStore.",
    icon: "icon-[material-symbols--storefront-outline]",
    category: "Extracurricular",
  },
  {
    url: "https://booking-innodatahub.innopolis.university/",
    resource: "InnoDataHub",
    title: null,
    description: "Book powerful computing resources.",
    icon: "icon-[material-symbols--storage]",
    category: "Technical",
  },
  {
    url: "https://baam.tatar/s",
    resource: "Baam",
    title: "Scan attendance",
    description: "Mark attendance by scanning QR code.",
    icon: "icon-[material-symbols--qr-code-scanner]",
    category: "Academic",
  },
  {
    url: "https://baam.tatar/AttendanceCheck",
    resource: "Baam",
    title: "Collect attendance",
    description: "Collect attendance for activity.",
    icon: "icon-[material-symbols--checklist]",
    category: "Academic",
  },
  {
    url: "https://moodle.innopolis.university/my/",
    resource: "Moodle",
    title: null,
    description: "Access official course materials and tests.",
    icon: "icon-[material-symbols--menu-book-outline]",
    category: "Academic",
  },
  {
    url: "https://hotel.innopolis.university/studentaccommodation/",
    resource: "Dormitory",
    title: "Student accommodation",
    description:
      "Fill the service requests, view the cleaning schedule, and read accommodation rules.",
    icon: "icon-[material-symbols--home-outline]",
    category: "Housing",
  },
  {
    url: "https://hotel.innopolis.university/studentaccommodation/#block2944",
    resource: "Dormitory",
    title: "Service request",
    description:
      "Submit requests for maintenance or services in your dormitory.",
    icon: "icon-[material-symbols--construction]",
    category: "Housing",
  },
  {
    url: "https://t.me/campus_info",
    resource: "Dormitory",
    title: "Information channel",
    description:
      "Get the latest updates and information about dormitory life and rules in Telegram.",
    icon: "icon-[material-symbols--info-outline]",
    category: "Housing",
  },
  {
    url: "https://t.me/Inno_dorm",
    resource: "Dormitory",
    title: "Student support",
    description: "Get assistance and support for dormitory-related issues.",
    icon: "icon-[material-symbols--support-agent]",
    category: "Housing",
  },
  {
    url: "https://t.me/hoteluni",
    resource: "Dormitory",
    title: "Administration",
    description:
      "Contact the hotel administration for official inquiries and concerns.",
    icon: "icon-[material-symbols--admin-panel-settings-outline]",
    category: "Housing",
  },
  {
    url: "http://campuslife.innopolis.ru/",
    resource: "Campus life",
    title: null,
    description:
      "Learn about student clubs, opportunities, events, and read the student handbook.",
    icon: "icon-[material-symbols--groups-outline]",
    category: "Extracurricular",
  },
  {
    url: "http://campuslife.innopolis.ru/handbook2023",
    resource: "Campus life",
    title: "Handbook",
    description:
      "Access the official student handbook for campus rules, policies, and guidelines.",
    icon: "icon-[material-symbols--menu-book-outline]",
    category: "Extracurricular",
  },
  {
    url: "http://campuslife.innopolis.ru/clubs",
    resource: "Campus life",
    title: "Clubs",
    description: "Explore and join student clubs and organizations on campus.",
    icon: "icon-[material-symbols--diversity-3]",
    category: "Extracurricular",
  },
  {
    url: "https://vm.innopolis.university/",
    resource: "IT help",
    title: "Virtual machines",
    description: "Access free virtual machines.",
    icon: "icon-[material-symbols--computer-outline]",
    category: "Technical",
  },
  {
    url: "https://portal.university.innopolis.ru/reading_hall/",
    resource: "Bitrix",
    title: "Library",
    description:
      "Explore books available in the university library and reserve some of them.",
    icon: "icon-[material-symbols--local-library-outline]",
    category: "Academic",
  },
  {
    url: "https://portal.university.innopolis.ru/reading_hall/",
    resource: "Library",
    title: "Information channel",
    description:
      "Get the latest updates and information about the library in Telegram.",
    icon: "icon-[material-symbols--local-library-outline]",
    category: "Academic",
  },
  {
    url: "https://portal.university.innopolis.ru/booking/index.php",
    resource: "Bitrix",
    title: "Ski equipment",
    description: "Book ski equipment for free.",
    icon: "icon-[material-symbols--downhill-skiing]",
    category: "Extracurricular",
  },
  {
    url: "https://sport.innopolis.university/profile/",
    resource: "Sport website",
    title: null,
    description:
      "Check in for classes at the sport complex and track the number of sport hours.",
    icon: "icon-[material-symbols--sports-gymnastics]",
    category: "Extracurricular",
  },
  {
    url: "https://t.me/IUSportBot",
    resource: "InNoHassle",
    title: "Sport bot",
    description: "Conveniently check in for sports in Telegram.",
    icon: "icon-[material-symbols--sports-soccer]",
    category: "Extracurricular",
  },
  {
    url: "https://t.me/InnoMusicRoomBot",
    resource: "InNoHassle",
    title: "Music room",
    description: "Access the music room with musical equipment.",
    icon: "icon-[material-symbols--music-note]",
    category: "Extracurricular",
  },
  {
    url: "https://t.me/InnaHelpBot",
    resource: "Inna",
    title: "Bus schedule",
    description:
      "Quickly find any city organization and view the bus schedule in Telegram.",
    icon: "icon-[material-symbols--directions-bus-outline]",
    category: "Navigation",
  },
  {
    url: "https://t.me/innobus",
    resource: "Bus",
    title: "Information channel",
    description: "View news about the current bus location in Telegram.",
    icon: "icon-[material-symbols--map-outline]",
    category: "Navigation",
  },
  {
    url: "https://t.me/innolinks",
    resource: "Chat with chats",
    title: null,
    description: "Explore links to many Telegram channels and chats.",
    icon: "icon-[material-symbols--chat-outline]",
    category: "Extracurricular",
  },
  {
    url: "https://innohassle.ru/calendar",
    resource: "InNoHassle",
    title: "Calendar",
    description: "View your personal schedule with classes, sports, deadlines.",
    icon: "icon-[material-symbols--calendar-month-outline-rounded]",
    category: "Academic",
  },
  {
    url: "https://innohassle.ru/room-booking",
    resource: "InNoHassle",
    title: "Room booking",
    description: "Book the meeting rooms and auditoriums in the university.",
    icon: "icon-[material-symbols--door-open-outline-rounded]",
    category: "Navigation",
  },
  {
    url: "https://innohassle.ru/maps",
    resource: "InNoHassle",
    title: "Maps",
    description: "Find any place in Innopolis.",
    icon: "icon-[material-symbols--map-outline]",
    category: "Navigation",
  },
  {
    url: "https://t.me/IURoomsBot",
    resource: "InNoHassle",
    title: "Dorms bot",
    description:
      "Manage your dormitory room and split duties with your roommates.",
    icon: "icon-[material-symbols--home-work-outline]",
    category: "Housing",
  },
  {
    url: "https://innohassle.ru/extension",
    resource: "InNoHassle",
    title: "Browser extension",
    description:
      "Install browser extension for auto-login to Moodle and quick links.",
    icon: "icon-[material-symbols--extension-outline]",
    category: "Technical",
  },
  {
    url: "https://it.innopolis.university",
    resource: "IT help",
    title: "Ticketing system",
    description: "Fill the tickets for the IT department.",
    icon: "icon-[material-symbols--computer-outline]",
    category: "Technical",
  },
  {
    url: "https://help.university.innopolis.ru",
    resource: "IT help",
    title: "Wiki",
    description: "Access the IT department's instructions.",
    icon: "icon-[material-symbols--contact-support-outline]",
    category: "Technical",
  },
  {
    url: "https://t.me/iuithelp",
    resource: "IT help",
    title: "Contact for urgent messages",
    description:
      "Reach out IT department for urgent assistance or inquiries via Telegram.",
    icon: "icon-[material-symbols--contact-support-outline]",
    category: "Technical",
  },
  {
    url: "https://mail.innopolis.ru",
    resource: "Outlook",
    title: "Mail",
    description: "Official corporate email service.",
    icon: "icon-[material-symbols--mail-outline]",
    category: "Technical",
  },
  {
    url: "https://mail.innopolis.ru/owa/#path=/calendar",
    resource: "Outlook",
    title: "Calendar",
    description: "Access the calendar and arrange meetings with IU employees.",
    icon: "icon-[material-symbols--calendar-month-outline]",
    category: "Technical",
  },
  {
    url: "https://t.me/IU_cigen_bot",
    resource: "Course image generator",
    title: null,
    description:
      "Quickly generate an image for your course chats and channels.",
    icon: "icon-[material-symbols--image-outline]",
    category: "Technical",
  },
  {
    url: "https://gitlab.pg.innopolis.university",
    resource: "GitLab",
    title: null,
    description: "Access the university GitLab for projects and assignments.",
    icon: "icon-[material-symbols--data-object]",
    category: "Technical",
  },
  {
    url: "https://t.me/opportunitiesforyou",
    resource: "Opportunities For You",
    title: null,
    description:
      "Telegram channel with announcements about interesting activities and events.",
    icon: "icon-[material-symbols--info-outline]",
    category: "Extracurricular",
  },
  {
    url: "https://t.me/StudentAffairs_bot",
    resource: "Student Affairs bot",
    title: null,
    description: "Bot for communication with 319 and DoE.",
    icon: "icon-[material-symbols--chat-outline]",
    category: "Support",
  },
];
