name: 🚀 Feature request
description: Propose a new feature to innohassle.ru
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to propose a feature 💜
        Please fill out the form below to help us understand and consider your proposal.
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature
      description: A clear and concise description of what the feature is.
      placeholder: Feature description
    validations:
      required: true
  - type: textarea
    id: suggested-solution
    attributes:
      label: Suggested solution
      description: We could provide following implementation...
      placeholder: Your thoughts on the solution
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any other context or screenshots about the feature request here.
      placeholder: Additional information
    validations:
      required: false
