/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as TvRouteImport } from "./routes/tv";
import { Route as ScheduleAssistantRouteRouteImport } from "./routes/schedule-assistant/route";
import { Route as With_menuRouteRouteImport } from "./routes/_with_menu/route";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ScheduleAssistantIndexRouteImport } from "./routes/schedule-assistant/index";
import { Route as ScheduleAssistantTimetableRouteImport } from "./routes/schedule-assistant/timetable";
import { Route as ScheduleAssistantChecksRouteImport } from "./routes/schedule-assistant/checks";
import { Route as RoomsRoomRouteImport } from "./routes/rooms.$room";
import { Route as FormsSubmitRouteImport } from "./routes/forms.submit";
import { Route as With_menuWorkshopsRouteImport } from "./routes/_with_menu/workshops";
import { Route as With_menuTimerRouteImport } from "./routes/_with_menu/timer";
import { Route as With_menuSportRouteImport } from "./routes/_with_menu/sport";
import { Route as With_menuScholarshipRouteImport } from "./routes/_with_menu/scholarship";
import { Route as With_menuMenuRouteImport } from "./routes/_with_menu/menu";
import { Route as With_menuMapsRouteImport } from "./routes/_with_menu/maps";
import { Route as With_menuFormsRouteImport } from "./routes/_with_menu/forms";
import { Route as With_menuExtensionRouteImport } from "./routes/_with_menu/extension";
import { Route as With_menuDormsRouteImport } from "./routes/_with_menu/dorms";
import { Route as With_menuDashboardRouteImport } from "./routes/_with_menu/dashboard";
import { Route as With_menuCalendarRouteImport } from "./routes/_with_menu/calendar";
import { Route as With_menuAboutRouteImport } from "./routes/_with_menu/about";
import { Route as With_menu42RouteImport } from "./routes/_with_menu/42";
import { Route as ScheduleAssistantSettingsIndexRouteImport } from "./routes/schedule-assistant/settings/index";
import { Route as With_menuWhen2meetIndexRouteImport } from "./routes/_with_menu/when2meet/index";
import { Route as With_menuTabletennisIndexRouteImport } from "./routes/_with_menu/tabletennis/index";
import { Route as With_menuStudentAffairsIndexRouteImport } from "./routes/_with_menu/student-affairs/index";
import { Route as With_menuSearchIndexRouteImport } from "./routes/_with_menu/search/index";
import { Route as With_menuScheduleIndexRouteImport } from "./routes/_with_menu/schedule/index";
import { Route as With_menuRoomBookingIndexRouteImport } from "./routes/_with_menu/room-booking/index";
import { Route as With_menuPrintersIndexRouteImport } from "./routes/_with_menu/printers/index";
import { Route as With_menuMusicRoomIndexRouteImport } from "./routes/_with_menu/music-room.index";
import { Route as With_menuGuardIndexRouteImport } from "./routes/_with_menu/guard/index";
import { Route as With_menuEventsIndexRouteImport } from "./routes/_with_menu/events/index";
import { Route as With_menuClubsIndexRouteImport } from "./routes/_with_menu/clubs/index";
import { Route as With_menuAccountIndexRouteImport } from "./routes/_with_menu/account/index";
import { Route as ScheduleAssistantSettingsSettingsTabRouteImport } from "./routes/schedule-assistant/settings/$settingsTab";
import { Route as With_menuWhen2meetNewRouteImport } from "./routes/_with_menu/when2meet/new";
import { Route as With_menuTabletennisTournamentsRouteImport } from "./routes/_with_menu/tabletennis/tournaments";
import { Route as With_menuTabletennisPlayersRouteImport } from "./routes/_with_menu/tabletennis/players";
import { Route as With_menuTabletennisMatchesRouteImport } from "./routes/_with_menu/tabletennis/matches";
import { Route as With_menuTabletennisEventsRouteImport } from "./routes/_with_menu/tabletennis/events";
import { Route as With_menuStudentAffairsSignOutRouteImport } from "./routes/_with_menu/student-affairs/sign-out";
import { Route as With_menuStudentAffairsSignInRouteImport } from "./routes/_with_menu/student-affairs/sign-in";
import { Route as With_menuSearchAskRouteImport } from "./routes/_with_menu/search/ask";
import { Route as With_menuSearchActRouteImport } from "./routes/_with_menu/search/act";
import { Route as With_menuScheduleCategoryRouteImport } from "./routes/_with_menu/schedule/$category";
import { Route as With_menuRoomBookingRulesRouteImport } from "./routes/_with_menu/room-booking/rules";
import { Route as With_menuRoomBookingListRouteImport } from "./routes/_with_menu/room-booking/list";
import { Route as With_menuPrintersScanRouteImport } from "./routes/_with_menu/printers/scan";
import { Route as With_menuPrintersPrintRouteImport } from "./routes/_with_menu/printers/print";
import { Route as With_menuMusicRoomInstructionsRouteImport } from "./routes/_with_menu/music-room.instructions";
import { Route as With_menuGuardFilesRouteImport } from "./routes/_with_menu/guard/files";
import { Route as With_menuGuardCreateRouteImport } from "./routes/_with_menu/guard/create";
import { Route as With_menuGuardCopyRouteImport } from "./routes/_with_menu/guard/copy";
import { Route as With_menuEventsCalendarRouteImport } from "./routes/_with_menu/events/calendar";
import { Route as With_menuEventsArchiveRouteImport } from "./routes/_with_menu/events/archive";
import { Route as With_menuEventsApprovalRouteImport } from "./routes/_with_menu/events/approval";
import { Route as With_menuEventsAdminRouteImport } from "./routes/_with_menu/events/admin";
import { Route as With_menuClubsNewRouteImport } from "./routes/_with_menu/clubs/new";
import { Route as With_menuClubsLeagueRouteImport } from "./routes/_with_menu/clubs/league";
import { Route as With_menuClubsAdminRouteImport } from "./routes/_with_menu/clubs/admin";
import { Route as With_menuAccountTokenRouteImport } from "./routes/_with_menu/account/token";
import { Route as With_menuAccountConnectTelegramRouteImport } from "./routes/_with_menu/account/connect-telegram";
import { Route as With_menuWhen2meetMeetingIdIndexRouteImport } from "./routes/_with_menu/when2meet/$meetingId.index";
import { Route as With_menuRoomBookingRoomsIndexRouteImport } from "./routes/_with_menu/room-booking/rooms.index";
import { Route as With_menuEventsIdIndexRouteImport } from "./routes/_with_menu/events/$id.index";
import { Route as With_menuClubsSlugIndexRouteImport } from "./routes/_with_menu/clubs/$slug.index";
import { Route as With_menuWhen2meetMeetingIdEditRouteImport } from "./routes/_with_menu/when2meet/$meetingId.edit";
import { Route as With_menuScheduleEventGroupsAliasRouteImport } from "./routes/_with_menu/schedule/event-groups.$alias";
import { Route as With_menuRoomBookingRoomsRoomRouteImport } from "./routes/_with_menu/room-booking/rooms.$room";
import { Route as With_menuEventsIdEditRouteImport } from "./routes/_with_menu/events/$id.edit";
import { Route as With_menuClubsSlugEditRouteImport } from "./routes/_with_menu/clubs/$slug.edit";
import { Route as GuardGoogleFilesSlugJoinRouteImport } from "./routes/guard.google.files.$slug.join";

const TvRoute = TvRouteImport.update({
  id: "/tv",
  path: "/tv",
  getParentRoute: () => rootRouteImport,
} as any);
const ScheduleAssistantRouteRoute = ScheduleAssistantRouteRouteImport.update({
  id: "/schedule-assistant",
  path: "/schedule-assistant",
  getParentRoute: () => rootRouteImport,
} as any);
const With_menuRouteRoute = With_menuRouteRouteImport.update({
  id: "/_with_menu",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const ScheduleAssistantIndexRoute = ScheduleAssistantIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ScheduleAssistantRouteRoute,
} as any);
const ScheduleAssistantTimetableRoute =
  ScheduleAssistantTimetableRouteImport.update({
    id: "/timetable",
    path: "/timetable",
    getParentRoute: () => ScheduleAssistantRouteRoute,
  } as any);
const ScheduleAssistantChecksRoute = ScheduleAssistantChecksRouteImport.update({
  id: "/checks",
  path: "/checks",
  getParentRoute: () => ScheduleAssistantRouteRoute,
} as any);
const RoomsRoomRoute = RoomsRoomRouteImport.update({
  id: "/rooms/$room",
  path: "/rooms/$room",
  getParentRoute: () => rootRouteImport,
} as any);
const FormsSubmitRoute = FormsSubmitRouteImport.update({
  id: "/forms/submit",
  path: "/forms/submit",
  getParentRoute: () => rootRouteImport,
} as any);
const With_menuWorkshopsRoute = With_menuWorkshopsRouteImport.update({
  id: "/workshops",
  path: "/workshops",
  getParentRoute: () => With_menuRouteRoute,
} as any);
const With_menuTimerRoute = With_menuTimerRouteImport.update({
  id: "/timer",
  path: "/timer",
  getParentRoute: () => With_menuRouteRoute,
} as any);
const With_menuSportRoute = With_menuSportRouteImport.update({
  id: "/sport",
  path: "/sport",
  getParentRoute: () => With_menuRouteRoute,
} as any);
const With_menuScholarshipRoute = With_menuScholarshipRouteImport.update({
  id: "/scholarship",
  path: "/scholarship",
  getParentRoute: () => With_menuRouteRoute,
} as any);
const With_menuMenuRoute = With_menuMenuRouteImport.update({
  id: "/menu",
  path: "/menu",
  getParentRoute: () => With_menuRouteRoute,
} as any);
const With_menuMapsRoute = With_menuMapsRouteImport.update({
  id: "/maps",
  path: "/maps",
  getParentRoute: () => With_menuRouteRoute,
} as any);
const With_menuFormsRoute = With_menuFormsRouteImport.update({
  id: "/forms",
  path: "/forms",
  getParentRoute: () => With_menuRouteRoute,
} as any);
const With_menuExtensionRoute = With_menuExtensionRouteImport.update({
  id: "/extension",
  path: "/extension",
  getParentRoute: () => With_menuRouteRoute,
} as any);
const With_menuDormsRoute = With_menuDormsRouteImport.update({
  id: "/dorms",
  path: "/dorms",
  getParentRoute: () => With_menuRouteRoute,
} as any);
const With_menuDashboardRoute = With_menuDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => With_menuRouteRoute,
} as any);
const With_menuCalendarRoute = With_menuCalendarRouteImport.update({
  id: "/calendar",
  path: "/calendar",
  getParentRoute: () => With_menuRouteRoute,
} as any);
const With_menuAboutRoute = With_menuAboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => With_menuRouteRoute,
} as any);
const With_menu42Route = With_menu42RouteImport.update({
  id: "/42",
  path: "/42",
  getParentRoute: () => With_menuRouteRoute,
} as any);
const ScheduleAssistantSettingsIndexRoute =
  ScheduleAssistantSettingsIndexRouteImport.update({
    id: "/settings/",
    path: "/settings/",
    getParentRoute: () => ScheduleAssistantRouteRoute,
  } as any);
const With_menuWhen2meetIndexRoute = With_menuWhen2meetIndexRouteImport.update({
  id: "/when2meet/",
  path: "/when2meet/",
  getParentRoute: () => With_menuRouteRoute,
} as any);
const With_menuTabletennisIndexRoute =
  With_menuTabletennisIndexRouteImport.update({
    id: "/tabletennis/",
    path: "/tabletennis/",
    getParentRoute: () => With_menuRouteRoute,
  } as any);
const With_menuStudentAffairsIndexRoute =
  With_menuStudentAffairsIndexRouteImport.update({
    id: "/student-affairs/",
    path: "/student-affairs/",
    getParentRoute: () => With_menuRouteRoute,
  } as any);
const With_menuSearchIndexRoute = With_menuSearchIndexRouteImport.update({
  id: "/search/",
  path: "/search/",
  getParentRoute: () => With_menuRouteRoute,
} as any);
const With_menuScheduleIndexRoute = With_menuScheduleIndexRouteImport.update({
  id: "/schedule/",
  path: "/schedule/",
  getParentRoute: () => With_menuRouteRoute,
} as any);
const With_menuRoomBookingIndexRoute =
  With_menuRoomBookingIndexRouteImport.update({
    id: "/room-booking/",
    path: "/room-booking/",
    getParentRoute: () => With_menuRouteRoute,
  } as any);
const With_menuPrintersIndexRoute = With_menuPrintersIndexRouteImport.update({
  id: "/printers/",
  path: "/printers/",
  getParentRoute: () => With_menuRouteRoute,
} as any);
const With_menuMusicRoomIndexRoute = With_menuMusicRoomIndexRouteImport.update({
  id: "/music-room/",
  path: "/music-room/",
  getParentRoute: () => With_menuRouteRoute,
} as any);
const With_menuGuardIndexRoute = With_menuGuardIndexRouteImport.update({
  id: "/guard/",
  path: "/guard/",
  getParentRoute: () => With_menuRouteRoute,
} as any);
const With_menuEventsIndexRoute = With_menuEventsIndexRouteImport.update({
  id: "/events/",
  path: "/events/",
  getParentRoute: () => With_menuRouteRoute,
} as any);
const With_menuClubsIndexRoute = With_menuClubsIndexRouteImport.update({
  id: "/clubs/",
  path: "/clubs/",
  getParentRoute: () => With_menuRouteRoute,
} as any);
const With_menuAccountIndexRoute = With_menuAccountIndexRouteImport.update({
  id: "/account/",
  path: "/account/",
  getParentRoute: () => With_menuRouteRoute,
} as any);
const ScheduleAssistantSettingsSettingsTabRoute =
  ScheduleAssistantSettingsSettingsTabRouteImport.update({
    id: "/settings/$settingsTab",
    path: "/settings/$settingsTab",
    getParentRoute: () => ScheduleAssistantRouteRoute,
  } as any);
const With_menuWhen2meetNewRoute = With_menuWhen2meetNewRouteImport.update({
  id: "/when2meet/new",
  path: "/when2meet/new",
  getParentRoute: () => With_menuRouteRoute,
} as any);
const With_menuTabletennisTournamentsRoute =
  With_menuTabletennisTournamentsRouteImport.update({
    id: "/tabletennis/tournaments",
    path: "/tabletennis/tournaments",
    getParentRoute: () => With_menuRouteRoute,
  } as any);
const With_menuTabletennisPlayersRoute =
  With_menuTabletennisPlayersRouteImport.update({
    id: "/tabletennis/players",
    path: "/tabletennis/players",
    getParentRoute: () => With_menuRouteRoute,
  } as any);
const With_menuTabletennisMatchesRoute =
  With_menuTabletennisMatchesRouteImport.update({
    id: "/tabletennis/matches",
    path: "/tabletennis/matches",
    getParentRoute: () => With_menuRouteRoute,
  } as any);
const With_menuTabletennisEventsRoute =
  With_menuTabletennisEventsRouteImport.update({
    id: "/tabletennis/events",
    path: "/tabletennis/events",
    getParentRoute: () => With_menuRouteRoute,
  } as any);
const With_menuStudentAffairsSignOutRoute =
  With_menuStudentAffairsSignOutRouteImport.update({
    id: "/student-affairs/sign-out",
    path: "/student-affairs/sign-out",
    getParentRoute: () => With_menuRouteRoute,
  } as any);
const With_menuStudentAffairsSignInRoute =
  With_menuStudentAffairsSignInRouteImport.update({
    id: "/student-affairs/sign-in",
    path: "/student-affairs/sign-in",
    getParentRoute: () => With_menuRouteRoute,
  } as any);
const With_menuSearchAskRoute = With_menuSearchAskRouteImport.update({
  id: "/search/ask",
  path: "/search/ask",
  getParentRoute: () => With_menuRouteRoute,
} as any);
const With_menuSearchActRoute = With_menuSearchActRouteImport.update({
  id: "/search/act",
  path: "/search/act",
  getParentRoute: () => With_menuRouteRoute,
} as any);
const With_menuScheduleCategoryRoute =
  With_menuScheduleCategoryRouteImport.update({
    id: "/schedule/$category",
    path: "/schedule/$category",
    getParentRoute: () => With_menuRouteRoute,
  } as any);
const With_menuRoomBookingRulesRoute =
  With_menuRoomBookingRulesRouteImport.update({
    id: "/room-booking/rules",
    path: "/room-booking/rules",
    getParentRoute: () => With_menuRouteRoute,
  } as any);
const With_menuRoomBookingListRoute =
  With_menuRoomBookingListRouteImport.update({
    id: "/room-booking/list",
    path: "/room-booking/list",
    getParentRoute: () => With_menuRouteRoute,
  } as any);
const With_menuPrintersScanRoute = With_menuPrintersScanRouteImport.update({
  id: "/printers/scan",
  path: "/printers/scan",
  getParentRoute: () => With_menuRouteRoute,
} as any);
const With_menuPrintersPrintRoute = With_menuPrintersPrintRouteImport.update({
  id: "/printers/print",
  path: "/printers/print",
  getParentRoute: () => With_menuRouteRoute,
} as any);
const With_menuMusicRoomInstructionsRoute =
  With_menuMusicRoomInstructionsRouteImport.update({
    id: "/music-room/instructions",
    path: "/music-room/instructions",
    getParentRoute: () => With_menuRouteRoute,
  } as any);
const With_menuGuardFilesRoute = With_menuGuardFilesRouteImport.update({
  id: "/guard/files",
  path: "/guard/files",
  getParentRoute: () => With_menuRouteRoute,
} as any);
const With_menuGuardCreateRoute = With_menuGuardCreateRouteImport.update({
  id: "/guard/create",
  path: "/guard/create",
  getParentRoute: () => With_menuRouteRoute,
} as any);
const With_menuGuardCopyRoute = With_menuGuardCopyRouteImport.update({
  id: "/guard/copy",
  path: "/guard/copy",
  getParentRoute: () => With_menuRouteRoute,
} as any);
const With_menuEventsCalendarRoute = With_menuEventsCalendarRouteImport.update({
  id: "/events/calendar",
  path: "/events/calendar",
  getParentRoute: () => With_menuRouteRoute,
} as any);
const With_menuEventsArchiveRoute = With_menuEventsArchiveRouteImport.update({
  id: "/events/archive",
  path: "/events/archive",
  getParentRoute: () => With_menuRouteRoute,
} as any);
const With_menuEventsApprovalRoute = With_menuEventsApprovalRouteImport.update({
  id: "/events/approval",
  path: "/events/approval",
  getParentRoute: () => With_menuRouteRoute,
} as any);
const With_menuEventsAdminRoute = With_menuEventsAdminRouteImport.update({
  id: "/events/admin",
  path: "/events/admin",
  getParentRoute: () => With_menuRouteRoute,
} as any);
const With_menuClubsNewRoute = With_menuClubsNewRouteImport.update({
  id: "/clubs/new",
  path: "/clubs/new",
  getParentRoute: () => With_menuRouteRoute,
} as any);
const With_menuClubsLeagueRoute = With_menuClubsLeagueRouteImport.update({
  id: "/clubs/league",
  path: "/clubs/league",
  getParentRoute: () => With_menuRouteRoute,
} as any);
const With_menuClubsAdminRoute = With_menuClubsAdminRouteImport.update({
  id: "/clubs/admin",
  path: "/clubs/admin",
  getParentRoute: () => With_menuRouteRoute,
} as any);
const With_menuAccountTokenRoute = With_menuAccountTokenRouteImport.update({
  id: "/account/token",
  path: "/account/token",
  getParentRoute: () => With_menuRouteRoute,
} as any);
const With_menuAccountConnectTelegramRoute =
  With_menuAccountConnectTelegramRouteImport.update({
    id: "/account/connect-telegram",
    path: "/account/connect-telegram",
    getParentRoute: () => With_menuRouteRoute,
  } as any);
const With_menuWhen2meetMeetingIdIndexRoute =
  With_menuWhen2meetMeetingIdIndexRouteImport.update({
    id: "/when2meet/$meetingId/",
    path: "/when2meet/$meetingId/",
    getParentRoute: () => With_menuRouteRoute,
  } as any);
const With_menuRoomBookingRoomsIndexRoute =
  With_menuRoomBookingRoomsIndexRouteImport.update({
    id: "/room-booking/rooms/",
    path: "/room-booking/rooms/",
    getParentRoute: () => With_menuRouteRoute,
  } as any);
const With_menuEventsIdIndexRoute = With_menuEventsIdIndexRouteImport.update({
  id: "/events/$id/",
  path: "/events/$id/",
  getParentRoute: () => With_menuRouteRoute,
} as any);
const With_menuClubsSlugIndexRoute = With_menuClubsSlugIndexRouteImport.update({
  id: "/clubs/$slug/",
  path: "/clubs/$slug/",
  getParentRoute: () => With_menuRouteRoute,
} as any);
const With_menuWhen2meetMeetingIdEditRoute =
  With_menuWhen2meetMeetingIdEditRouteImport.update({
    id: "/when2meet/$meetingId/edit",
    path: "/when2meet/$meetingId/edit",
    getParentRoute: () => With_menuRouteRoute,
  } as any);
const With_menuScheduleEventGroupsAliasRoute =
  With_menuScheduleEventGroupsAliasRouteImport.update({
    id: "/schedule/event-groups/$alias",
    path: "/schedule/event-groups/$alias",
    getParentRoute: () => With_menuRouteRoute,
  } as any);
const With_menuRoomBookingRoomsRoomRoute =
  With_menuRoomBookingRoomsRoomRouteImport.update({
    id: "/room-booking/rooms/$room",
    path: "/room-booking/rooms/$room",
    getParentRoute: () => With_menuRouteRoute,
  } as any);
const With_menuEventsIdEditRoute = With_menuEventsIdEditRouteImport.update({
  id: "/events/$id/edit",
  path: "/events/$id/edit",
  getParentRoute: () => With_menuRouteRoute,
} as any);
const With_menuClubsSlugEditRoute = With_menuClubsSlugEditRouteImport.update({
  id: "/clubs/$slug/edit",
  path: "/clubs/$slug/edit",
  getParentRoute: () => With_menuRouteRoute,
} as any);
const GuardGoogleFilesSlugJoinRoute =
  GuardGoogleFilesSlugJoinRouteImport.update({
    id: "/guard/google/files/$slug/join",
    path: "/guard/google/files/$slug/join",
    getParentRoute: () => rootRouteImport,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/schedule-assistant": typeof ScheduleAssistantRouteRouteWithChildren;
  "/tv": typeof TvRoute;
  "/42": typeof With_menu42Route;
  "/about": typeof With_menuAboutRoute;
  "/calendar": typeof With_menuCalendarRoute;
  "/dashboard": typeof With_menuDashboardRoute;
  "/dorms": typeof With_menuDormsRoute;
  "/extension": typeof With_menuExtensionRoute;
  "/forms": typeof With_menuFormsRoute;
  "/maps": typeof With_menuMapsRoute;
  "/menu": typeof With_menuMenuRoute;
  "/scholarship": typeof With_menuScholarshipRoute;
  "/sport": typeof With_menuSportRoute;
  "/timer": typeof With_menuTimerRoute;
  "/workshops": typeof With_menuWorkshopsRoute;
  "/forms/submit": typeof FormsSubmitRoute;
  "/rooms/$room": typeof RoomsRoomRoute;
  "/schedule-assistant/checks": typeof ScheduleAssistantChecksRoute;
  "/schedule-assistant/timetable": typeof ScheduleAssistantTimetableRoute;
  "/schedule-assistant/": typeof ScheduleAssistantIndexRoute;
  "/account/connect-telegram": typeof With_menuAccountConnectTelegramRoute;
  "/account/token": typeof With_menuAccountTokenRoute;
  "/clubs/admin": typeof With_menuClubsAdminRoute;
  "/clubs/league": typeof With_menuClubsLeagueRoute;
  "/clubs/new": typeof With_menuClubsNewRoute;
  "/events/admin": typeof With_menuEventsAdminRoute;
  "/events/approval": typeof With_menuEventsApprovalRoute;
  "/events/archive": typeof With_menuEventsArchiveRoute;
  "/events/calendar": typeof With_menuEventsCalendarRoute;
  "/guard/copy": typeof With_menuGuardCopyRoute;
  "/guard/create": typeof With_menuGuardCreateRoute;
  "/guard/files": typeof With_menuGuardFilesRoute;
  "/music-room/instructions": typeof With_menuMusicRoomInstructionsRoute;
  "/printers/print": typeof With_menuPrintersPrintRoute;
  "/printers/scan": typeof With_menuPrintersScanRoute;
  "/room-booking/list": typeof With_menuRoomBookingListRoute;
  "/room-booking/rules": typeof With_menuRoomBookingRulesRoute;
  "/schedule/$category": typeof With_menuScheduleCategoryRoute;
  "/search/act": typeof With_menuSearchActRoute;
  "/search/ask": typeof With_menuSearchAskRoute;
  "/student-affairs/sign-in": typeof With_menuStudentAffairsSignInRoute;
  "/student-affairs/sign-out": typeof With_menuStudentAffairsSignOutRoute;
  "/tabletennis/events": typeof With_menuTabletennisEventsRoute;
  "/tabletennis/matches": typeof With_menuTabletennisMatchesRoute;
  "/tabletennis/players": typeof With_menuTabletennisPlayersRoute;
  "/tabletennis/tournaments": typeof With_menuTabletennisTournamentsRoute;
  "/when2meet/new": typeof With_menuWhen2meetNewRoute;
  "/schedule-assistant/settings/$settingsTab": typeof ScheduleAssistantSettingsSettingsTabRoute;
  "/account/": typeof With_menuAccountIndexRoute;
  "/clubs/": typeof With_menuClubsIndexRoute;
  "/events/": typeof With_menuEventsIndexRoute;
  "/guard/": typeof With_menuGuardIndexRoute;
  "/music-room/": typeof With_menuMusicRoomIndexRoute;
  "/printers/": typeof With_menuPrintersIndexRoute;
  "/room-booking/": typeof With_menuRoomBookingIndexRoute;
  "/schedule/": typeof With_menuScheduleIndexRoute;
  "/search/": typeof With_menuSearchIndexRoute;
  "/student-affairs/": typeof With_menuStudentAffairsIndexRoute;
  "/tabletennis/": typeof With_menuTabletennisIndexRoute;
  "/when2meet/": typeof With_menuWhen2meetIndexRoute;
  "/schedule-assistant/settings/": typeof ScheduleAssistantSettingsIndexRoute;
  "/clubs/$slug/edit": typeof With_menuClubsSlugEditRoute;
  "/events/$id/edit": typeof With_menuEventsIdEditRoute;
  "/room-booking/rooms/$room": typeof With_menuRoomBookingRoomsRoomRoute;
  "/schedule/event-groups/$alias": typeof With_menuScheduleEventGroupsAliasRoute;
  "/when2meet/$meetingId/edit": typeof With_menuWhen2meetMeetingIdEditRoute;
  "/clubs/$slug/": typeof With_menuClubsSlugIndexRoute;
  "/events/$id/": typeof With_menuEventsIdIndexRoute;
  "/room-booking/rooms/": typeof With_menuRoomBookingRoomsIndexRoute;
  "/when2meet/$meetingId/": typeof With_menuWhen2meetMeetingIdIndexRoute;
  "/guard/google/files/$slug/join": typeof GuardGoogleFilesSlugJoinRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/tv": typeof TvRoute;
  "/42": typeof With_menu42Route;
  "/about": typeof With_menuAboutRoute;
  "/calendar": typeof With_menuCalendarRoute;
  "/dashboard": typeof With_menuDashboardRoute;
  "/dorms": typeof With_menuDormsRoute;
  "/extension": typeof With_menuExtensionRoute;
  "/forms": typeof With_menuFormsRoute;
  "/maps": typeof With_menuMapsRoute;
  "/menu": typeof With_menuMenuRoute;
  "/scholarship": typeof With_menuScholarshipRoute;
  "/sport": typeof With_menuSportRoute;
  "/timer": typeof With_menuTimerRoute;
  "/workshops": typeof With_menuWorkshopsRoute;
  "/forms/submit": typeof FormsSubmitRoute;
  "/rooms/$room": typeof RoomsRoomRoute;
  "/schedule-assistant/checks": typeof ScheduleAssistantChecksRoute;
  "/schedule-assistant/timetable": typeof ScheduleAssistantTimetableRoute;
  "/schedule-assistant": typeof ScheduleAssistantIndexRoute;
  "/account/connect-telegram": typeof With_menuAccountConnectTelegramRoute;
  "/account/token": typeof With_menuAccountTokenRoute;
  "/clubs/admin": typeof With_menuClubsAdminRoute;
  "/clubs/league": typeof With_menuClubsLeagueRoute;
  "/clubs/new": typeof With_menuClubsNewRoute;
  "/events/admin": typeof With_menuEventsAdminRoute;
  "/events/approval": typeof With_menuEventsApprovalRoute;
  "/events/archive": typeof With_menuEventsArchiveRoute;
  "/events/calendar": typeof With_menuEventsCalendarRoute;
  "/guard/copy": typeof With_menuGuardCopyRoute;
  "/guard/create": typeof With_menuGuardCreateRoute;
  "/guard/files": typeof With_menuGuardFilesRoute;
  "/music-room/instructions": typeof With_menuMusicRoomInstructionsRoute;
  "/printers/print": typeof With_menuPrintersPrintRoute;
  "/printers/scan": typeof With_menuPrintersScanRoute;
  "/room-booking/list": typeof With_menuRoomBookingListRoute;
  "/room-booking/rules": typeof With_menuRoomBookingRulesRoute;
  "/schedule/$category": typeof With_menuScheduleCategoryRoute;
  "/search/act": typeof With_menuSearchActRoute;
  "/search/ask": typeof With_menuSearchAskRoute;
  "/student-affairs/sign-in": typeof With_menuStudentAffairsSignInRoute;
  "/student-affairs/sign-out": typeof With_menuStudentAffairsSignOutRoute;
  "/tabletennis/events": typeof With_menuTabletennisEventsRoute;
  "/tabletennis/matches": typeof With_menuTabletennisMatchesRoute;
  "/tabletennis/players": typeof With_menuTabletennisPlayersRoute;
  "/tabletennis/tournaments": typeof With_menuTabletennisTournamentsRoute;
  "/when2meet/new": typeof With_menuWhen2meetNewRoute;
  "/schedule-assistant/settings/$settingsTab": typeof ScheduleAssistantSettingsSettingsTabRoute;
  "/account": typeof With_menuAccountIndexRoute;
  "/clubs": typeof With_menuClubsIndexRoute;
  "/events": typeof With_menuEventsIndexRoute;
  "/guard": typeof With_menuGuardIndexRoute;
  "/music-room": typeof With_menuMusicRoomIndexRoute;
  "/printers": typeof With_menuPrintersIndexRoute;
  "/room-booking": typeof With_menuRoomBookingIndexRoute;
  "/schedule": typeof With_menuScheduleIndexRoute;
  "/search": typeof With_menuSearchIndexRoute;
  "/student-affairs": typeof With_menuStudentAffairsIndexRoute;
  "/tabletennis": typeof With_menuTabletennisIndexRoute;
  "/when2meet": typeof With_menuWhen2meetIndexRoute;
  "/schedule-assistant/settings": typeof ScheduleAssistantSettingsIndexRoute;
  "/clubs/$slug/edit": typeof With_menuClubsSlugEditRoute;
  "/events/$id/edit": typeof With_menuEventsIdEditRoute;
  "/room-booking/rooms/$room": typeof With_menuRoomBookingRoomsRoomRoute;
  "/schedule/event-groups/$alias": typeof With_menuScheduleEventGroupsAliasRoute;
  "/when2meet/$meetingId/edit": typeof With_menuWhen2meetMeetingIdEditRoute;
  "/clubs/$slug": typeof With_menuClubsSlugIndexRoute;
  "/events/$id": typeof With_menuEventsIdIndexRoute;
  "/room-booking/rooms": typeof With_menuRoomBookingRoomsIndexRoute;
  "/when2meet/$meetingId": typeof With_menuWhen2meetMeetingIdIndexRoute;
  "/guard/google/files/$slug/join": typeof GuardGoogleFilesSlugJoinRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_with_menu": typeof With_menuRouteRouteWithChildren;
  "/schedule-assistant": typeof ScheduleAssistantRouteRouteWithChildren;
  "/tv": typeof TvRoute;
  "/_with_menu/42": typeof With_menu42Route;
  "/_with_menu/about": typeof With_menuAboutRoute;
  "/_with_menu/calendar": typeof With_menuCalendarRoute;
  "/_with_menu/dashboard": typeof With_menuDashboardRoute;
  "/_with_menu/dorms": typeof With_menuDormsRoute;
  "/_with_menu/extension": typeof With_menuExtensionRoute;
  "/_with_menu/forms": typeof With_menuFormsRoute;
  "/_with_menu/maps": typeof With_menuMapsRoute;
  "/_with_menu/menu": typeof With_menuMenuRoute;
  "/_with_menu/scholarship": typeof With_menuScholarshipRoute;
  "/_with_menu/sport": typeof With_menuSportRoute;
  "/_with_menu/timer": typeof With_menuTimerRoute;
  "/_with_menu/workshops": typeof With_menuWorkshopsRoute;
  "/forms/submit": typeof FormsSubmitRoute;
  "/rooms/$room": typeof RoomsRoomRoute;
  "/schedule-assistant/checks": typeof ScheduleAssistantChecksRoute;
  "/schedule-assistant/timetable": typeof ScheduleAssistantTimetableRoute;
  "/schedule-assistant/": typeof ScheduleAssistantIndexRoute;
  "/_with_menu/account/connect-telegram": typeof With_menuAccountConnectTelegramRoute;
  "/_with_menu/account/token": typeof With_menuAccountTokenRoute;
  "/_with_menu/clubs/admin": typeof With_menuClubsAdminRoute;
  "/_with_menu/clubs/league": typeof With_menuClubsLeagueRoute;
  "/_with_menu/clubs/new": typeof With_menuClubsNewRoute;
  "/_with_menu/events/admin": typeof With_menuEventsAdminRoute;
  "/_with_menu/events/approval": typeof With_menuEventsApprovalRoute;
  "/_with_menu/events/archive": typeof With_menuEventsArchiveRoute;
  "/_with_menu/events/calendar": typeof With_menuEventsCalendarRoute;
  "/_with_menu/guard/copy": typeof With_menuGuardCopyRoute;
  "/_with_menu/guard/create": typeof With_menuGuardCreateRoute;
  "/_with_menu/guard/files": typeof With_menuGuardFilesRoute;
  "/_with_menu/music-room/instructions": typeof With_menuMusicRoomInstructionsRoute;
  "/_with_menu/printers/print": typeof With_menuPrintersPrintRoute;
  "/_with_menu/printers/scan": typeof With_menuPrintersScanRoute;
  "/_with_menu/room-booking/list": typeof With_menuRoomBookingListRoute;
  "/_with_menu/room-booking/rules": typeof With_menuRoomBookingRulesRoute;
  "/_with_menu/schedule/$category": typeof With_menuScheduleCategoryRoute;
  "/_with_menu/search/act": typeof With_menuSearchActRoute;
  "/_with_menu/search/ask": typeof With_menuSearchAskRoute;
  "/_with_menu/student-affairs/sign-in": typeof With_menuStudentAffairsSignInRoute;
  "/_with_menu/student-affairs/sign-out": typeof With_menuStudentAffairsSignOutRoute;
  "/_with_menu/tabletennis/events": typeof With_menuTabletennisEventsRoute;
  "/_with_menu/tabletennis/matches": typeof With_menuTabletennisMatchesRoute;
  "/_with_menu/tabletennis/players": typeof With_menuTabletennisPlayersRoute;
  "/_with_menu/tabletennis/tournaments": typeof With_menuTabletennisTournamentsRoute;
  "/_with_menu/when2meet/new": typeof With_menuWhen2meetNewRoute;
  "/schedule-assistant/settings/$settingsTab": typeof ScheduleAssistantSettingsSettingsTabRoute;
  "/_with_menu/account/": typeof With_menuAccountIndexRoute;
  "/_with_menu/clubs/": typeof With_menuClubsIndexRoute;
  "/_with_menu/events/": typeof With_menuEventsIndexRoute;
  "/_with_menu/guard/": typeof With_menuGuardIndexRoute;
  "/_with_menu/music-room/": typeof With_menuMusicRoomIndexRoute;
  "/_with_menu/printers/": typeof With_menuPrintersIndexRoute;
  "/_with_menu/room-booking/": typeof With_menuRoomBookingIndexRoute;
  "/_with_menu/schedule/": typeof With_menuScheduleIndexRoute;
  "/_with_menu/search/": typeof With_menuSearchIndexRoute;
  "/_with_menu/student-affairs/": typeof With_menuStudentAffairsIndexRoute;
  "/_with_menu/tabletennis/": typeof With_menuTabletennisIndexRoute;
  "/_with_menu/when2meet/": typeof With_menuWhen2meetIndexRoute;
  "/schedule-assistant/settings/": typeof ScheduleAssistantSettingsIndexRoute;
  "/_with_menu/clubs/$slug/edit": typeof With_menuClubsSlugEditRoute;
  "/_with_menu/events/$id/edit": typeof With_menuEventsIdEditRoute;
  "/_with_menu/room-booking/rooms/$room": typeof With_menuRoomBookingRoomsRoomRoute;
  "/_with_menu/schedule/event-groups/$alias": typeof With_menuScheduleEventGroupsAliasRoute;
  "/_with_menu/when2meet/$meetingId/edit": typeof With_menuWhen2meetMeetingIdEditRoute;
  "/_with_menu/clubs/$slug/": typeof With_menuClubsSlugIndexRoute;
  "/_with_menu/events/$id/": typeof With_menuEventsIdIndexRoute;
  "/_with_menu/room-booking/rooms/": typeof With_menuRoomBookingRoomsIndexRoute;
  "/_with_menu/when2meet/$meetingId/": typeof With_menuWhen2meetMeetingIdIndexRoute;
  "/guard/google/files/$slug/join": typeof GuardGoogleFilesSlugJoinRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/schedule-assistant"
    | "/tv"
    | "/42"
    | "/about"
    | "/calendar"
    | "/dashboard"
    | "/dorms"
    | "/extension"
    | "/forms"
    | "/maps"
    | "/menu"
    | "/scholarship"
    | "/sport"
    | "/timer"
    | "/workshops"
    | "/forms/submit"
    | "/rooms/$room"
    | "/schedule-assistant/checks"
    | "/schedule-assistant/timetable"
    | "/schedule-assistant/"
    | "/account/connect-telegram"
    | "/account/token"
    | "/clubs/admin"
    | "/clubs/league"
    | "/clubs/new"
    | "/events/admin"
    | "/events/approval"
    | "/events/archive"
    | "/events/calendar"
    | "/guard/copy"
    | "/guard/create"
    | "/guard/files"
    | "/music-room/instructions"
    | "/printers/print"
    | "/printers/scan"
    | "/room-booking/list"
    | "/room-booking/rules"
    | "/schedule/$category"
    | "/search/act"
    | "/search/ask"
    | "/student-affairs/sign-in"
    | "/student-affairs/sign-out"
    | "/tabletennis/events"
    | "/tabletennis/matches"
    | "/tabletennis/players"
    | "/tabletennis/tournaments"
    | "/when2meet/new"
    | "/schedule-assistant/settings/$settingsTab"
    | "/account/"
    | "/clubs/"
    | "/events/"
    | "/guard/"
    | "/music-room/"
    | "/printers/"
    | "/room-booking/"
    | "/schedule/"
    | "/search/"
    | "/student-affairs/"
    | "/tabletennis/"
    | "/when2meet/"
    | "/schedule-assistant/settings/"
    | "/clubs/$slug/edit"
    | "/events/$id/edit"
    | "/room-booking/rooms/$room"
    | "/schedule/event-groups/$alias"
    | "/when2meet/$meetingId/edit"
    | "/clubs/$slug/"
    | "/events/$id/"
    | "/room-booking/rooms/"
    | "/when2meet/$meetingId/"
    | "/guard/google/files/$slug/join";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/tv"
    | "/42"
    | "/about"
    | "/calendar"
    | "/dashboard"
    | "/dorms"
    | "/extension"
    | "/forms"
    | "/maps"
    | "/menu"
    | "/scholarship"
    | "/sport"
    | "/timer"
    | "/workshops"
    | "/forms/submit"
    | "/rooms/$room"
    | "/schedule-assistant/checks"
    | "/schedule-assistant/timetable"
    | "/schedule-assistant"
    | "/account/connect-telegram"
    | "/account/token"
    | "/clubs/admin"
    | "/clubs/league"
    | "/clubs/new"
    | "/events/admin"
    | "/events/approval"
    | "/events/archive"
    | "/events/calendar"
    | "/guard/copy"
    | "/guard/create"
    | "/guard/files"
    | "/music-room/instructions"
    | "/printers/print"
    | "/printers/scan"
    | "/room-booking/list"
    | "/room-booking/rules"
    | "/schedule/$category"
    | "/search/act"
    | "/search/ask"
    | "/student-affairs/sign-in"
    | "/student-affairs/sign-out"
    | "/tabletennis/events"
    | "/tabletennis/matches"
    | "/tabletennis/players"
    | "/tabletennis/tournaments"
    | "/when2meet/new"
    | "/schedule-assistant/settings/$settingsTab"
    | "/account"
    | "/clubs"
    | "/events"
    | "/guard"
    | "/music-room"
    | "/printers"
    | "/room-booking"
    | "/schedule"
    | "/search"
    | "/student-affairs"
    | "/tabletennis"
    | "/when2meet"
    | "/schedule-assistant/settings"
    | "/clubs/$slug/edit"
    | "/events/$id/edit"
    | "/room-booking/rooms/$room"
    | "/schedule/event-groups/$alias"
    | "/when2meet/$meetingId/edit"
    | "/clubs/$slug"
    | "/events/$id"
    | "/room-booking/rooms"
    | "/when2meet/$meetingId"
    | "/guard/google/files/$slug/join";
  id:
    | "__root__"
    | "/"
    | "/_with_menu"
    | "/schedule-assistant"
    | "/tv"
    | "/_with_menu/42"
    | "/_with_menu/about"
    | "/_with_menu/calendar"
    | "/_with_menu/dashboard"
    | "/_with_menu/dorms"
    | "/_with_menu/extension"
    | "/_with_menu/forms"
    | "/_with_menu/maps"
    | "/_with_menu/menu"
    | "/_with_menu/scholarship"
    | "/_with_menu/sport"
    | "/_with_menu/timer"
    | "/_with_menu/workshops"
    | "/forms/submit"
    | "/rooms/$room"
    | "/schedule-assistant/checks"
    | "/schedule-assistant/timetable"
    | "/schedule-assistant/"
    | "/_with_menu/account/connect-telegram"
    | "/_with_menu/account/token"
    | "/_with_menu/clubs/admin"
    | "/_with_menu/clubs/league"
    | "/_with_menu/clubs/new"
    | "/_with_menu/events/admin"
    | "/_with_menu/events/approval"
    | "/_with_menu/events/archive"
    | "/_with_menu/events/calendar"
    | "/_with_menu/guard/copy"
    | "/_with_menu/guard/create"
    | "/_with_menu/guard/files"
    | "/_with_menu/music-room/instructions"
    | "/_with_menu/printers/print"
    | "/_with_menu/printers/scan"
    | "/_with_menu/room-booking/list"
    | "/_with_menu/room-booking/rules"
    | "/_with_menu/schedule/$category"
    | "/_with_menu/search/act"
    | "/_with_menu/search/ask"
    | "/_with_menu/student-affairs/sign-in"
    | "/_with_menu/student-affairs/sign-out"
    | "/_with_menu/tabletennis/events"
    | "/_with_menu/tabletennis/matches"
    | "/_with_menu/tabletennis/players"
    | "/_with_menu/tabletennis/tournaments"
    | "/_with_menu/when2meet/new"
    | "/schedule-assistant/settings/$settingsTab"
    | "/_with_menu/account/"
    | "/_with_menu/clubs/"
    | "/_with_menu/events/"
    | "/_with_menu/guard/"
    | "/_with_menu/music-room/"
    | "/_with_menu/printers/"
    | "/_with_menu/room-booking/"
    | "/_with_menu/schedule/"
    | "/_with_menu/search/"
    | "/_with_menu/student-affairs/"
    | "/_with_menu/tabletennis/"
    | "/_with_menu/when2meet/"
    | "/schedule-assistant/settings/"
    | "/_with_menu/clubs/$slug/edit"
    | "/_with_menu/events/$id/edit"
    | "/_with_menu/room-booking/rooms/$room"
    | "/_with_menu/schedule/event-groups/$alias"
    | "/_with_menu/when2meet/$meetingId/edit"
    | "/_with_menu/clubs/$slug/"
    | "/_with_menu/events/$id/"
    | "/_with_menu/room-booking/rooms/"
    | "/_with_menu/when2meet/$meetingId/"
    | "/guard/google/files/$slug/join";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  With_menuRouteRoute: typeof With_menuRouteRouteWithChildren;
  ScheduleAssistantRouteRoute: typeof ScheduleAssistantRouteRouteWithChildren;
  TvRoute: typeof TvRoute;
  FormsSubmitRoute: typeof FormsSubmitRoute;
  RoomsRoomRoute: typeof RoomsRoomRoute;
  GuardGoogleFilesSlugJoinRoute: typeof GuardGoogleFilesSlugJoinRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/tv": {
      id: "/tv";
      path: "/tv";
      fullPath: "/tv";
      preLoaderRoute: typeof TvRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/schedule-assistant": {
      id: "/schedule-assistant";
      path: "/schedule-assistant";
      fullPath: "/schedule-assistant";
      preLoaderRoute: typeof ScheduleAssistantRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_with_menu": {
      id: "/_with_menu";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof With_menuRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/schedule-assistant/": {
      id: "/schedule-assistant/";
      path: "/";
      fullPath: "/schedule-assistant/";
      preLoaderRoute: typeof ScheduleAssistantIndexRouteImport;
      parentRoute: typeof ScheduleAssistantRouteRoute;
    };
    "/schedule-assistant/timetable": {
      id: "/schedule-assistant/timetable";
      path: "/timetable";
      fullPath: "/schedule-assistant/timetable";
      preLoaderRoute: typeof ScheduleAssistantTimetableRouteImport;
      parentRoute: typeof ScheduleAssistantRouteRoute;
    };
    "/schedule-assistant/checks": {
      id: "/schedule-assistant/checks";
      path: "/checks";
      fullPath: "/schedule-assistant/checks";
      preLoaderRoute: typeof ScheduleAssistantChecksRouteImport;
      parentRoute: typeof ScheduleAssistantRouteRoute;
    };
    "/rooms/$room": {
      id: "/rooms/$room";
      path: "/rooms/$room";
      fullPath: "/rooms/$room";
      preLoaderRoute: typeof RoomsRoomRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/forms/submit": {
      id: "/forms/submit";
      path: "/forms/submit";
      fullPath: "/forms/submit";
      preLoaderRoute: typeof FormsSubmitRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_with_menu/workshops": {
      id: "/_with_menu/workshops";
      path: "/workshops";
      fullPath: "/workshops";
      preLoaderRoute: typeof With_menuWorkshopsRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/timer": {
      id: "/_with_menu/timer";
      path: "/timer";
      fullPath: "/timer";
      preLoaderRoute: typeof With_menuTimerRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/sport": {
      id: "/_with_menu/sport";
      path: "/sport";
      fullPath: "/sport";
      preLoaderRoute: typeof With_menuSportRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/scholarship": {
      id: "/_with_menu/scholarship";
      path: "/scholarship";
      fullPath: "/scholarship";
      preLoaderRoute: typeof With_menuScholarshipRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/menu": {
      id: "/_with_menu/menu";
      path: "/menu";
      fullPath: "/menu";
      preLoaderRoute: typeof With_menuMenuRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/maps": {
      id: "/_with_menu/maps";
      path: "/maps";
      fullPath: "/maps";
      preLoaderRoute: typeof With_menuMapsRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/forms": {
      id: "/_with_menu/forms";
      path: "/forms";
      fullPath: "/forms";
      preLoaderRoute: typeof With_menuFormsRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/extension": {
      id: "/_with_menu/extension";
      path: "/extension";
      fullPath: "/extension";
      preLoaderRoute: typeof With_menuExtensionRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/dorms": {
      id: "/_with_menu/dorms";
      path: "/dorms";
      fullPath: "/dorms";
      preLoaderRoute: typeof With_menuDormsRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/dashboard": {
      id: "/_with_menu/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof With_menuDashboardRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/calendar": {
      id: "/_with_menu/calendar";
      path: "/calendar";
      fullPath: "/calendar";
      preLoaderRoute: typeof With_menuCalendarRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/about": {
      id: "/_with_menu/about";
      path: "/about";
      fullPath: "/about";
      preLoaderRoute: typeof With_menuAboutRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/42": {
      id: "/_with_menu/42";
      path: "/42";
      fullPath: "/42";
      preLoaderRoute: typeof With_menu42RouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/schedule-assistant/settings/": {
      id: "/schedule-assistant/settings/";
      path: "/settings";
      fullPath: "/schedule-assistant/settings/";
      preLoaderRoute: typeof ScheduleAssistantSettingsIndexRouteImport;
      parentRoute: typeof ScheduleAssistantRouteRoute;
    };
    "/_with_menu/when2meet/": {
      id: "/_with_menu/when2meet/";
      path: "/when2meet";
      fullPath: "/when2meet/";
      preLoaderRoute: typeof With_menuWhen2meetIndexRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/tabletennis/": {
      id: "/_with_menu/tabletennis/";
      path: "/tabletennis";
      fullPath: "/tabletennis/";
      preLoaderRoute: typeof With_menuTabletennisIndexRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/student-affairs/": {
      id: "/_with_menu/student-affairs/";
      path: "/student-affairs";
      fullPath: "/student-affairs/";
      preLoaderRoute: typeof With_menuStudentAffairsIndexRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/search/": {
      id: "/_with_menu/search/";
      path: "/search";
      fullPath: "/search/";
      preLoaderRoute: typeof With_menuSearchIndexRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/schedule/": {
      id: "/_with_menu/schedule/";
      path: "/schedule";
      fullPath: "/schedule/";
      preLoaderRoute: typeof With_menuScheduleIndexRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/room-booking/": {
      id: "/_with_menu/room-booking/";
      path: "/room-booking";
      fullPath: "/room-booking/";
      preLoaderRoute: typeof With_menuRoomBookingIndexRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/printers/": {
      id: "/_with_menu/printers/";
      path: "/printers";
      fullPath: "/printers/";
      preLoaderRoute: typeof With_menuPrintersIndexRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/music-room/": {
      id: "/_with_menu/music-room/";
      path: "/music-room";
      fullPath: "/music-room/";
      preLoaderRoute: typeof With_menuMusicRoomIndexRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/guard/": {
      id: "/_with_menu/guard/";
      path: "/guard";
      fullPath: "/guard/";
      preLoaderRoute: typeof With_menuGuardIndexRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/events/": {
      id: "/_with_menu/events/";
      path: "/events";
      fullPath: "/events/";
      preLoaderRoute: typeof With_menuEventsIndexRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/clubs/": {
      id: "/_with_menu/clubs/";
      path: "/clubs";
      fullPath: "/clubs/";
      preLoaderRoute: typeof With_menuClubsIndexRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/account/": {
      id: "/_with_menu/account/";
      path: "/account";
      fullPath: "/account/";
      preLoaderRoute: typeof With_menuAccountIndexRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/schedule-assistant/settings/$settingsTab": {
      id: "/schedule-assistant/settings/$settingsTab";
      path: "/settings/$settingsTab";
      fullPath: "/schedule-assistant/settings/$settingsTab";
      preLoaderRoute: typeof ScheduleAssistantSettingsSettingsTabRouteImport;
      parentRoute: typeof ScheduleAssistantRouteRoute;
    };
    "/_with_menu/when2meet/new": {
      id: "/_with_menu/when2meet/new";
      path: "/when2meet/new";
      fullPath: "/when2meet/new";
      preLoaderRoute: typeof With_menuWhen2meetNewRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/tabletennis/tournaments": {
      id: "/_with_menu/tabletennis/tournaments";
      path: "/tabletennis/tournaments";
      fullPath: "/tabletennis/tournaments";
      preLoaderRoute: typeof With_menuTabletennisTournamentsRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/tabletennis/players": {
      id: "/_with_menu/tabletennis/players";
      path: "/tabletennis/players";
      fullPath: "/tabletennis/players";
      preLoaderRoute: typeof With_menuTabletennisPlayersRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/tabletennis/matches": {
      id: "/_with_menu/tabletennis/matches";
      path: "/tabletennis/matches";
      fullPath: "/tabletennis/matches";
      preLoaderRoute: typeof With_menuTabletennisMatchesRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/tabletennis/events": {
      id: "/_with_menu/tabletennis/events";
      path: "/tabletennis/events";
      fullPath: "/tabletennis/events";
      preLoaderRoute: typeof With_menuTabletennisEventsRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/student-affairs/sign-out": {
      id: "/_with_menu/student-affairs/sign-out";
      path: "/student-affairs/sign-out";
      fullPath: "/student-affairs/sign-out";
      preLoaderRoute: typeof With_menuStudentAffairsSignOutRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/student-affairs/sign-in": {
      id: "/_with_menu/student-affairs/sign-in";
      path: "/student-affairs/sign-in";
      fullPath: "/student-affairs/sign-in";
      preLoaderRoute: typeof With_menuStudentAffairsSignInRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/search/ask": {
      id: "/_with_menu/search/ask";
      path: "/search/ask";
      fullPath: "/search/ask";
      preLoaderRoute: typeof With_menuSearchAskRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/search/act": {
      id: "/_with_menu/search/act";
      path: "/search/act";
      fullPath: "/search/act";
      preLoaderRoute: typeof With_menuSearchActRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/schedule/$category": {
      id: "/_with_menu/schedule/$category";
      path: "/schedule/$category";
      fullPath: "/schedule/$category";
      preLoaderRoute: typeof With_menuScheduleCategoryRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/room-booking/rules": {
      id: "/_with_menu/room-booking/rules";
      path: "/room-booking/rules";
      fullPath: "/room-booking/rules";
      preLoaderRoute: typeof With_menuRoomBookingRulesRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/room-booking/list": {
      id: "/_with_menu/room-booking/list";
      path: "/room-booking/list";
      fullPath: "/room-booking/list";
      preLoaderRoute: typeof With_menuRoomBookingListRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/printers/scan": {
      id: "/_with_menu/printers/scan";
      path: "/printers/scan";
      fullPath: "/printers/scan";
      preLoaderRoute: typeof With_menuPrintersScanRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/printers/print": {
      id: "/_with_menu/printers/print";
      path: "/printers/print";
      fullPath: "/printers/print";
      preLoaderRoute: typeof With_menuPrintersPrintRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/music-room/instructions": {
      id: "/_with_menu/music-room/instructions";
      path: "/music-room/instructions";
      fullPath: "/music-room/instructions";
      preLoaderRoute: typeof With_menuMusicRoomInstructionsRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/guard/files": {
      id: "/_with_menu/guard/files";
      path: "/guard/files";
      fullPath: "/guard/files";
      preLoaderRoute: typeof With_menuGuardFilesRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/guard/create": {
      id: "/_with_menu/guard/create";
      path: "/guard/create";
      fullPath: "/guard/create";
      preLoaderRoute: typeof With_menuGuardCreateRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/guard/copy": {
      id: "/_with_menu/guard/copy";
      path: "/guard/copy";
      fullPath: "/guard/copy";
      preLoaderRoute: typeof With_menuGuardCopyRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/events/calendar": {
      id: "/_with_menu/events/calendar";
      path: "/events/calendar";
      fullPath: "/events/calendar";
      preLoaderRoute: typeof With_menuEventsCalendarRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/events/archive": {
      id: "/_with_menu/events/archive";
      path: "/events/archive";
      fullPath: "/events/archive";
      preLoaderRoute: typeof With_menuEventsArchiveRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/events/approval": {
      id: "/_with_menu/events/approval";
      path: "/events/approval";
      fullPath: "/events/approval";
      preLoaderRoute: typeof With_menuEventsApprovalRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/events/admin": {
      id: "/_with_menu/events/admin";
      path: "/events/admin";
      fullPath: "/events/admin";
      preLoaderRoute: typeof With_menuEventsAdminRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/clubs/new": {
      id: "/_with_menu/clubs/new";
      path: "/clubs/new";
      fullPath: "/clubs/new";
      preLoaderRoute: typeof With_menuClubsNewRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/clubs/league": {
      id: "/_with_menu/clubs/league";
      path: "/clubs/league";
      fullPath: "/clubs/league";
      preLoaderRoute: typeof With_menuClubsLeagueRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/clubs/admin": {
      id: "/_with_menu/clubs/admin";
      path: "/clubs/admin";
      fullPath: "/clubs/admin";
      preLoaderRoute: typeof With_menuClubsAdminRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/account/token": {
      id: "/_with_menu/account/token";
      path: "/account/token";
      fullPath: "/account/token";
      preLoaderRoute: typeof With_menuAccountTokenRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/account/connect-telegram": {
      id: "/_with_menu/account/connect-telegram";
      path: "/account/connect-telegram";
      fullPath: "/account/connect-telegram";
      preLoaderRoute: typeof With_menuAccountConnectTelegramRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/when2meet/$meetingId/": {
      id: "/_with_menu/when2meet/$meetingId/";
      path: "/when2meet/$meetingId";
      fullPath: "/when2meet/$meetingId/";
      preLoaderRoute: typeof With_menuWhen2meetMeetingIdIndexRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/room-booking/rooms/": {
      id: "/_with_menu/room-booking/rooms/";
      path: "/room-booking/rooms";
      fullPath: "/room-booking/rooms/";
      preLoaderRoute: typeof With_menuRoomBookingRoomsIndexRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/events/$id/": {
      id: "/_with_menu/events/$id/";
      path: "/events/$id";
      fullPath: "/events/$id/";
      preLoaderRoute: typeof With_menuEventsIdIndexRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/clubs/$slug/": {
      id: "/_with_menu/clubs/$slug/";
      path: "/clubs/$slug";
      fullPath: "/clubs/$slug/";
      preLoaderRoute: typeof With_menuClubsSlugIndexRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/when2meet/$meetingId/edit": {
      id: "/_with_menu/when2meet/$meetingId/edit";
      path: "/when2meet/$meetingId/edit";
      fullPath: "/when2meet/$meetingId/edit";
      preLoaderRoute: typeof With_menuWhen2meetMeetingIdEditRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/schedule/event-groups/$alias": {
      id: "/_with_menu/schedule/event-groups/$alias";
      path: "/schedule/event-groups/$alias";
      fullPath: "/schedule/event-groups/$alias";
      preLoaderRoute: typeof With_menuScheduleEventGroupsAliasRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/room-booking/rooms/$room": {
      id: "/_with_menu/room-booking/rooms/$room";
      path: "/room-booking/rooms/$room";
      fullPath: "/room-booking/rooms/$room";
      preLoaderRoute: typeof With_menuRoomBookingRoomsRoomRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/events/$id/edit": {
      id: "/_with_menu/events/$id/edit";
      path: "/events/$id/edit";
      fullPath: "/events/$id/edit";
      preLoaderRoute: typeof With_menuEventsIdEditRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/_with_menu/clubs/$slug/edit": {
      id: "/_with_menu/clubs/$slug/edit";
      path: "/clubs/$slug/edit";
      fullPath: "/clubs/$slug/edit";
      preLoaderRoute: typeof With_menuClubsSlugEditRouteImport;
      parentRoute: typeof With_menuRouteRoute;
    };
    "/guard/google/files/$slug/join": {
      id: "/guard/google/files/$slug/join";
      path: "/guard/google/files/$slug/join";
      fullPath: "/guard/google/files/$slug/join";
      preLoaderRoute: typeof GuardGoogleFilesSlugJoinRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

interface With_menuRouteRouteChildren {
  With_menu42Route: typeof With_menu42Route;
  With_menuAboutRoute: typeof With_menuAboutRoute;
  With_menuCalendarRoute: typeof With_menuCalendarRoute;
  With_menuDashboardRoute: typeof With_menuDashboardRoute;
  With_menuDormsRoute: typeof With_menuDormsRoute;
  With_menuExtensionRoute: typeof With_menuExtensionRoute;
  With_menuFormsRoute: typeof With_menuFormsRoute;
  With_menuMapsRoute: typeof With_menuMapsRoute;
  With_menuMenuRoute: typeof With_menuMenuRoute;
  With_menuScholarshipRoute: typeof With_menuScholarshipRoute;
  With_menuSportRoute: typeof With_menuSportRoute;
  With_menuTimerRoute: typeof With_menuTimerRoute;
  With_menuWorkshopsRoute: typeof With_menuWorkshopsRoute;
  With_menuAccountConnectTelegramRoute: typeof With_menuAccountConnectTelegramRoute;
  With_menuAccountTokenRoute: typeof With_menuAccountTokenRoute;
  With_menuClubsAdminRoute: typeof With_menuClubsAdminRoute;
  With_menuClubsLeagueRoute: typeof With_menuClubsLeagueRoute;
  With_menuClubsNewRoute: typeof With_menuClubsNewRoute;
  With_menuEventsAdminRoute: typeof With_menuEventsAdminRoute;
  With_menuEventsApprovalRoute: typeof With_menuEventsApprovalRoute;
  With_menuEventsArchiveRoute: typeof With_menuEventsArchiveRoute;
  With_menuEventsCalendarRoute: typeof With_menuEventsCalendarRoute;
  With_menuGuardCopyRoute: typeof With_menuGuardCopyRoute;
  With_menuGuardCreateRoute: typeof With_menuGuardCreateRoute;
  With_menuGuardFilesRoute: typeof With_menuGuardFilesRoute;
  With_menuMusicRoomInstructionsRoute: typeof With_menuMusicRoomInstructionsRoute;
  With_menuPrintersPrintRoute: typeof With_menuPrintersPrintRoute;
  With_menuPrintersScanRoute: typeof With_menuPrintersScanRoute;
  With_menuRoomBookingListRoute: typeof With_menuRoomBookingListRoute;
  With_menuRoomBookingRulesRoute: typeof With_menuRoomBookingRulesRoute;
  With_menuScheduleCategoryRoute: typeof With_menuScheduleCategoryRoute;
  With_menuSearchActRoute: typeof With_menuSearchActRoute;
  With_menuSearchAskRoute: typeof With_menuSearchAskRoute;
  With_menuStudentAffairsSignInRoute: typeof With_menuStudentAffairsSignInRoute;
  With_menuStudentAffairsSignOutRoute: typeof With_menuStudentAffairsSignOutRoute;
  With_menuTabletennisEventsRoute: typeof With_menuTabletennisEventsRoute;
  With_menuTabletennisMatchesRoute: typeof With_menuTabletennisMatchesRoute;
  With_menuTabletennisPlayersRoute: typeof With_menuTabletennisPlayersRoute;
  With_menuTabletennisTournamentsRoute: typeof With_menuTabletennisTournamentsRoute;
  With_menuWhen2meetNewRoute: typeof With_menuWhen2meetNewRoute;
  With_menuAccountIndexRoute: typeof With_menuAccountIndexRoute;
  With_menuClubsIndexRoute: typeof With_menuClubsIndexRoute;
  With_menuEventsIndexRoute: typeof With_menuEventsIndexRoute;
  With_menuGuardIndexRoute: typeof With_menuGuardIndexRoute;
  With_menuMusicRoomIndexRoute: typeof With_menuMusicRoomIndexRoute;
  With_menuPrintersIndexRoute: typeof With_menuPrintersIndexRoute;
  With_menuRoomBookingIndexRoute: typeof With_menuRoomBookingIndexRoute;
  With_menuScheduleIndexRoute: typeof With_menuScheduleIndexRoute;
  With_menuSearchIndexRoute: typeof With_menuSearchIndexRoute;
  With_menuStudentAffairsIndexRoute: typeof With_menuStudentAffairsIndexRoute;
  With_menuTabletennisIndexRoute: typeof With_menuTabletennisIndexRoute;
  With_menuWhen2meetIndexRoute: typeof With_menuWhen2meetIndexRoute;
  With_menuClubsSlugEditRoute: typeof With_menuClubsSlugEditRoute;
  With_menuEventsIdEditRoute: typeof With_menuEventsIdEditRoute;
  With_menuRoomBookingRoomsRoomRoute: typeof With_menuRoomBookingRoomsRoomRoute;
  With_menuScheduleEventGroupsAliasRoute: typeof With_menuScheduleEventGroupsAliasRoute;
  With_menuWhen2meetMeetingIdEditRoute: typeof With_menuWhen2meetMeetingIdEditRoute;
  With_menuClubsSlugIndexRoute: typeof With_menuClubsSlugIndexRoute;
  With_menuEventsIdIndexRoute: typeof With_menuEventsIdIndexRoute;
  With_menuRoomBookingRoomsIndexRoute: typeof With_menuRoomBookingRoomsIndexRoute;
  With_menuWhen2meetMeetingIdIndexRoute: typeof With_menuWhen2meetMeetingIdIndexRoute;
}

const With_menuRouteRouteChildren: With_menuRouteRouteChildren = {
  With_menu42Route: With_menu42Route,
  With_menuAboutRoute: With_menuAboutRoute,
  With_menuCalendarRoute: With_menuCalendarRoute,
  With_menuDashboardRoute: With_menuDashboardRoute,
  With_menuDormsRoute: With_menuDormsRoute,
  With_menuExtensionRoute: With_menuExtensionRoute,
  With_menuFormsRoute: With_menuFormsRoute,
  With_menuMapsRoute: With_menuMapsRoute,
  With_menuMenuRoute: With_menuMenuRoute,
  With_menuScholarshipRoute: With_menuScholarshipRoute,
  With_menuSportRoute: With_menuSportRoute,
  With_menuTimerRoute: With_menuTimerRoute,
  With_menuWorkshopsRoute: With_menuWorkshopsRoute,
  With_menuAccountConnectTelegramRoute: With_menuAccountConnectTelegramRoute,
  With_menuAccountTokenRoute: With_menuAccountTokenRoute,
  With_menuClubsAdminRoute: With_menuClubsAdminRoute,
  With_menuClubsLeagueRoute: With_menuClubsLeagueRoute,
  With_menuClubsNewRoute: With_menuClubsNewRoute,
  With_menuEventsAdminRoute: With_menuEventsAdminRoute,
  With_menuEventsApprovalRoute: With_menuEventsApprovalRoute,
  With_menuEventsArchiveRoute: With_menuEventsArchiveRoute,
  With_menuEventsCalendarRoute: With_menuEventsCalendarRoute,
  With_menuGuardCopyRoute: With_menuGuardCopyRoute,
  With_menuGuardCreateRoute: With_menuGuardCreateRoute,
  With_menuGuardFilesRoute: With_menuGuardFilesRoute,
  With_menuMusicRoomInstructionsRoute: With_menuMusicRoomInstructionsRoute,
  With_menuPrintersPrintRoute: With_menuPrintersPrintRoute,
  With_menuPrintersScanRoute: With_menuPrintersScanRoute,
  With_menuRoomBookingListRoute: With_menuRoomBookingListRoute,
  With_menuRoomBookingRulesRoute: With_menuRoomBookingRulesRoute,
  With_menuScheduleCategoryRoute: With_menuScheduleCategoryRoute,
  With_menuSearchActRoute: With_menuSearchActRoute,
  With_menuSearchAskRoute: With_menuSearchAskRoute,
  With_menuStudentAffairsSignInRoute: With_menuStudentAffairsSignInRoute,
  With_menuStudentAffairsSignOutRoute: With_menuStudentAffairsSignOutRoute,
  With_menuTabletennisEventsRoute: With_menuTabletennisEventsRoute,
  With_menuTabletennisMatchesRoute: With_menuTabletennisMatchesRoute,
  With_menuTabletennisPlayersRoute: With_menuTabletennisPlayersRoute,
  With_menuTabletennisTournamentsRoute: With_menuTabletennisTournamentsRoute,
  With_menuWhen2meetNewRoute: With_menuWhen2meetNewRoute,
  With_menuAccountIndexRoute: With_menuAccountIndexRoute,
  With_menuClubsIndexRoute: With_menuClubsIndexRoute,
  With_menuEventsIndexRoute: With_menuEventsIndexRoute,
  With_menuGuardIndexRoute: With_menuGuardIndexRoute,
  With_menuMusicRoomIndexRoute: With_menuMusicRoomIndexRoute,
  With_menuPrintersIndexRoute: With_menuPrintersIndexRoute,
  With_menuRoomBookingIndexRoute: With_menuRoomBookingIndexRoute,
  With_menuScheduleIndexRoute: With_menuScheduleIndexRoute,
  With_menuSearchIndexRoute: With_menuSearchIndexRoute,
  With_menuStudentAffairsIndexRoute: With_menuStudentAffairsIndexRoute,
  With_menuTabletennisIndexRoute: With_menuTabletennisIndexRoute,
  With_menuWhen2meetIndexRoute: With_menuWhen2meetIndexRoute,
  With_menuClubsSlugEditRoute: With_menuClubsSlugEditRoute,
  With_menuEventsIdEditRoute: With_menuEventsIdEditRoute,
  With_menuRoomBookingRoomsRoomRoute: With_menuRoomBookingRoomsRoomRoute,
  With_menuScheduleEventGroupsAliasRoute:
    With_menuScheduleEventGroupsAliasRoute,
  With_menuWhen2meetMeetingIdEditRoute: With_menuWhen2meetMeetingIdEditRoute,
  With_menuClubsSlugIndexRoute: With_menuClubsSlugIndexRoute,
  With_menuEventsIdIndexRoute: With_menuEventsIdIndexRoute,
  With_menuRoomBookingRoomsIndexRoute: With_menuRoomBookingRoomsIndexRoute,
  With_menuWhen2meetMeetingIdIndexRoute: With_menuWhen2meetMeetingIdIndexRoute,
};

const With_menuRouteRouteWithChildren = With_menuRouteRoute._addFileChildren(
  With_menuRouteRouteChildren,
);

interface ScheduleAssistantRouteRouteChildren {
  ScheduleAssistantChecksRoute: typeof ScheduleAssistantChecksRoute;
  ScheduleAssistantTimetableRoute: typeof ScheduleAssistantTimetableRoute;
  ScheduleAssistantIndexRoute: typeof ScheduleAssistantIndexRoute;
  ScheduleAssistantSettingsSettingsTabRoute: typeof ScheduleAssistantSettingsSettingsTabRoute;
  ScheduleAssistantSettingsIndexRoute: typeof ScheduleAssistantSettingsIndexRoute;
}

const ScheduleAssistantRouteRouteChildren: ScheduleAssistantRouteRouteChildren =
  {
    ScheduleAssistantChecksRoute: ScheduleAssistantChecksRoute,
    ScheduleAssistantTimetableRoute: ScheduleAssistantTimetableRoute,
    ScheduleAssistantIndexRoute: ScheduleAssistantIndexRoute,
    ScheduleAssistantSettingsSettingsTabRoute:
      ScheduleAssistantSettingsSettingsTabRoute,
    ScheduleAssistantSettingsIndexRoute: ScheduleAssistantSettingsIndexRoute,
  };

const ScheduleAssistantRouteRouteWithChildren =
  ScheduleAssistantRouteRoute._addFileChildren(
    ScheduleAssistantRouteRouteChildren,
  );

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  With_menuRouteRoute: With_menuRouteRouteWithChildren,
  ScheduleAssistantRouteRoute: ScheduleAssistantRouteRouteWithChildren,
  TvRoute: TvRoute,
  FormsSubmitRoute: FormsSubmitRoute,
  RoomsRoomRoute: RoomsRoomRoute,
  GuardGoogleFilesSlugJoinRoute: GuardGoogleFilesSlugJoinRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
