/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as FormsImport } from "./routes/forms";
import { Route as WithmenuRouteImport } from "./routes/_with_menu/route";
import { Route as IndexImport } from "./routes/index";
import { Route as WithmenuSportImport } from "./routes/_with_menu/sport";
import { Route as WithmenuSearchImport } from "./routes/_with_menu/search";
import { Route as WithmenuScholarshipImport } from "./routes/_with_menu/scholarship";
import { Route as WithmenuPrintersImport } from "./routes/_with_menu/printers";
import { Route as WithmenuMenuImport } from "./routes/_with_menu/menu";
import { Route as WithmenuMapsImport } from "./routes/_with_menu/maps";
import { Route as WithmenuExtensionImport } from "./routes/_with_menu/extension";
import { Route as WithmenuDormsImport } from "./routes/_with_menu/dorms";
import { Route as WithmenuDashboardImport } from "./routes/_with_menu/dashboard";
import { Route as WithmenuCalendarImport } from "./routes/_with_menu/calendar";
import { Route as WithmenuAccountRouteImport } from "./routes/_with_menu/account/route";
import { Route as WithmenuScheduleIndexImport } from "./routes/_with_menu/schedule/index";
import { Route as WithmenuRoomBookingIndexImport } from "./routes/_with_menu/room-booking/index";
import { Route as WithmenuMusicRoomIndexImport } from "./routes/_with_menu/music-room.index";
import { Route as WithmenuAccountIndexImport } from "./routes/_with_menu/account/index";
import { Route as WithmenuScheduleCategoryImport } from "./routes/_with_menu/schedule/$category";
import { Route as WithmenuRoomBookingRulesImport } from "./routes/_with_menu/room-booking/rules";
import { Route as WithmenuRoomBookingListImport } from "./routes/_with_menu/room-booking/list";
import { Route as WithmenuMusicRoomInstructionsImport } from "./routes/_with_menu/music-room.instructions";
import { Route as WithmenuAccountTokenImport } from "./routes/_with_menu/account/token";
import { Route as WithmenuAccountConnectTelegramImport } from "./routes/_with_menu/account/connect-telegram";
import { Route as WithmenuScheduleEventGroupsAliasImport } from "./routes/_with_menu/schedule/event-groups.$alias";

// Create/Update Routes

const FormsRoute = FormsImport.update({
  path: "/forms",
  getParentRoute: () => rootRoute,
} as any);

const WithmenuRouteRoute = WithmenuRouteImport.update({
  id: "/_with_menu",
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const WithmenuSportRoute = WithmenuSportImport.update({
  path: "/sport",
  getParentRoute: () => WithmenuRouteRoute,
} as any);

const WithmenuSearchRoute = WithmenuSearchImport.update({
  path: "/search",
  getParentRoute: () => WithmenuRouteRoute,
} as any);

const WithmenuScholarshipRoute = WithmenuScholarshipImport.update({
  path: "/scholarship",
  getParentRoute: () => WithmenuRouteRoute,
} as any);

const WithmenuPrintersRoute = WithmenuPrintersImport.update({
  path: "/printers",
  getParentRoute: () => WithmenuRouteRoute,
} as any);

const WithmenuMenuRoute = WithmenuMenuImport.update({
  path: "/menu",
  getParentRoute: () => WithmenuRouteRoute,
} as any);

const WithmenuMapsRoute = WithmenuMapsImport.update({
  path: "/maps",
  getParentRoute: () => WithmenuRouteRoute,
} as any);

const WithmenuExtensionRoute = WithmenuExtensionImport.update({
  path: "/extension",
  getParentRoute: () => WithmenuRouteRoute,
} as any);

const WithmenuDormsRoute = WithmenuDormsImport.update({
  path: "/dorms",
  getParentRoute: () => WithmenuRouteRoute,
} as any);

const WithmenuDashboardRoute = WithmenuDashboardImport.update({
  path: "/dashboard",
  getParentRoute: () => WithmenuRouteRoute,
} as any);

const WithmenuCalendarRoute = WithmenuCalendarImport.update({
  path: "/calendar",
  getParentRoute: () => WithmenuRouteRoute,
} as any);

const WithmenuAccountRouteRoute = WithmenuAccountRouteImport.update({
  path: "/account",
  getParentRoute: () => WithmenuRouteRoute,
} as any);

const WithmenuScheduleIndexRoute = WithmenuScheduleIndexImport.update({
  path: "/schedule/",
  getParentRoute: () => WithmenuRouteRoute,
} as any);

const WithmenuRoomBookingIndexRoute = WithmenuRoomBookingIndexImport.update({
  path: "/room-booking/",
  getParentRoute: () => WithmenuRouteRoute,
} as any);

const WithmenuMusicRoomIndexRoute = WithmenuMusicRoomIndexImport.update({
  path: "/music-room/",
  getParentRoute: () => WithmenuRouteRoute,
} as any);

const WithmenuAccountIndexRoute = WithmenuAccountIndexImport.update({
  path: "/",
  getParentRoute: () => WithmenuAccountRouteRoute,
} as any);

const WithmenuScheduleCategoryRoute = WithmenuScheduleCategoryImport.update({
  path: "/schedule/$category",
  getParentRoute: () => WithmenuRouteRoute,
} as any);

const WithmenuRoomBookingRulesRoute = WithmenuRoomBookingRulesImport.update({
  path: "/room-booking/rules",
  getParentRoute: () => WithmenuRouteRoute,
} as any);

const WithmenuRoomBookingListRoute = WithmenuRoomBookingListImport.update({
  path: "/room-booking/list",
  getParentRoute: () => WithmenuRouteRoute,
} as any);

const WithmenuMusicRoomInstructionsRoute =
  WithmenuMusicRoomInstructionsImport.update({
    path: "/music-room/instructions",
    getParentRoute: () => WithmenuRouteRoute,
  } as any);

const WithmenuAccountTokenRoute = WithmenuAccountTokenImport.update({
  path: "/token",
  getParentRoute: () => WithmenuAccountRouteRoute,
} as any);

const WithmenuAccountConnectTelegramRoute =
  WithmenuAccountConnectTelegramImport.update({
    path: "/connect-telegram",
    getParentRoute: () => WithmenuAccountRouteRoute,
  } as any);

const WithmenuScheduleEventGroupsAliasRoute =
  WithmenuScheduleEventGroupsAliasImport.update({
    path: "/schedule/event-groups/$alias",
    getParentRoute: () => WithmenuRouteRoute,
  } as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/_with_menu": {
      id: "/_with_menu";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof WithmenuRouteImport;
      parentRoute: typeof rootRoute;
    };
    "/forms": {
      id: "/forms";
      path: "/forms";
      fullPath: "/forms";
      preLoaderRoute: typeof FormsImport;
      parentRoute: typeof rootRoute;
    };
    "/_with_menu/account": {
      id: "/_with_menu/account";
      path: "/account";
      fullPath: "/account";
      preLoaderRoute: typeof WithmenuAccountRouteImport;
      parentRoute: typeof WithmenuRouteImport;
    };
    "/_with_menu/calendar": {
      id: "/_with_menu/calendar";
      path: "/calendar";
      fullPath: "/calendar";
      preLoaderRoute: typeof WithmenuCalendarImport;
      parentRoute: typeof WithmenuRouteImport;
    };
    "/_with_menu/dashboard": {
      id: "/_with_menu/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof WithmenuDashboardImport;
      parentRoute: typeof WithmenuRouteImport;
    };
    "/_with_menu/dorms": {
      id: "/_with_menu/dorms";
      path: "/dorms";
      fullPath: "/dorms";
      preLoaderRoute: typeof WithmenuDormsImport;
      parentRoute: typeof WithmenuRouteImport;
    };
    "/_with_menu/extension": {
      id: "/_with_menu/extension";
      path: "/extension";
      fullPath: "/extension";
      preLoaderRoute: typeof WithmenuExtensionImport;
      parentRoute: typeof WithmenuRouteImport;
    };
    "/_with_menu/maps": {
      id: "/_with_menu/maps";
      path: "/maps";
      fullPath: "/maps";
      preLoaderRoute: typeof WithmenuMapsImport;
      parentRoute: typeof WithmenuRouteImport;
    };
    "/_with_menu/menu": {
      id: "/_with_menu/menu";
      path: "/menu";
      fullPath: "/menu";
      preLoaderRoute: typeof WithmenuMenuImport;
      parentRoute: typeof WithmenuRouteImport;
    };
    "/_with_menu/printers": {
      id: "/_with_menu/printers";
      path: "/printers";
      fullPath: "/printers";
      preLoaderRoute: typeof WithmenuPrintersImport;
      parentRoute: typeof WithmenuRouteImport;
    };
    "/_with_menu/scholarship": {
      id: "/_with_menu/scholarship";
      path: "/scholarship";
      fullPath: "/scholarship";
      preLoaderRoute: typeof WithmenuScholarshipImport;
      parentRoute: typeof WithmenuRouteImport;
    };
    "/_with_menu/search": {
      id: "/_with_menu/search";
      path: "/search";
      fullPath: "/search";
      preLoaderRoute: typeof WithmenuSearchImport;
      parentRoute: typeof WithmenuRouteImport;
    };
    "/_with_menu/sport": {
      id: "/_with_menu/sport";
      path: "/sport";
      fullPath: "/sport";
      preLoaderRoute: typeof WithmenuSportImport;
      parentRoute: typeof WithmenuRouteImport;
    };
    "/_with_menu/account/connect-telegram": {
      id: "/_with_menu/account/connect-telegram";
      path: "/connect-telegram";
      fullPath: "/account/connect-telegram";
      preLoaderRoute: typeof WithmenuAccountConnectTelegramImport;
      parentRoute: typeof WithmenuAccountRouteImport;
    };
    "/_with_menu/account/token": {
      id: "/_with_menu/account/token";
      path: "/token";
      fullPath: "/account/token";
      preLoaderRoute: typeof WithmenuAccountTokenImport;
      parentRoute: typeof WithmenuAccountRouteImport;
    };
    "/_with_menu/music-room/instructions": {
      id: "/_with_menu/music-room/instructions";
      path: "/music-room/instructions";
      fullPath: "/music-room/instructions";
      preLoaderRoute: typeof WithmenuMusicRoomInstructionsImport;
      parentRoute: typeof WithmenuRouteImport;
    };
    "/_with_menu/room-booking/list": {
      id: "/_with_menu/room-booking/list";
      path: "/room-booking/list";
      fullPath: "/room-booking/list";
      preLoaderRoute: typeof WithmenuRoomBookingListImport;
      parentRoute: typeof WithmenuRouteImport;
    };
    "/_with_menu/room-booking/rules": {
      id: "/_with_menu/room-booking/rules";
      path: "/room-booking/rules";
      fullPath: "/room-booking/rules";
      preLoaderRoute: typeof WithmenuRoomBookingRulesImport;
      parentRoute: typeof WithmenuRouteImport;
    };
    "/_with_menu/schedule/$category": {
      id: "/_with_menu/schedule/$category";
      path: "/schedule/$category";
      fullPath: "/schedule/$category";
      preLoaderRoute: typeof WithmenuScheduleCategoryImport;
      parentRoute: typeof WithmenuRouteImport;
    };
    "/_with_menu/account/": {
      id: "/_with_menu/account/";
      path: "/";
      fullPath: "/account/";
      preLoaderRoute: typeof WithmenuAccountIndexImport;
      parentRoute: typeof WithmenuAccountRouteImport;
    };
    "/_with_menu/music-room/": {
      id: "/_with_menu/music-room/";
      path: "/music-room";
      fullPath: "/music-room";
      preLoaderRoute: typeof WithmenuMusicRoomIndexImport;
      parentRoute: typeof WithmenuRouteImport;
    };
    "/_with_menu/room-booking/": {
      id: "/_with_menu/room-booking/";
      path: "/room-booking";
      fullPath: "/room-booking";
      preLoaderRoute: typeof WithmenuRoomBookingIndexImport;
      parentRoute: typeof WithmenuRouteImport;
    };
    "/_with_menu/schedule/": {
      id: "/_with_menu/schedule/";
      path: "/schedule";
      fullPath: "/schedule";
      preLoaderRoute: typeof WithmenuScheduleIndexImport;
      parentRoute: typeof WithmenuRouteImport;
    };
    "/_with_menu/schedule/event-groups/$alias": {
      id: "/_with_menu/schedule/event-groups/$alias";
      path: "/schedule/event-groups/$alias";
      fullPath: "/schedule/event-groups/$alias";
      preLoaderRoute: typeof WithmenuScheduleEventGroupsAliasImport;
      parentRoute: typeof WithmenuRouteImport;
    };
  }
}

// Create and export the route tree

interface WithmenuAccountRouteRouteChildren {
  WithmenuAccountConnectTelegramRoute: typeof WithmenuAccountConnectTelegramRoute;
  WithmenuAccountTokenRoute: typeof WithmenuAccountTokenRoute;
  WithmenuAccountIndexRoute: typeof WithmenuAccountIndexRoute;
}

const WithmenuAccountRouteRouteChildren: WithmenuAccountRouteRouteChildren = {
  WithmenuAccountConnectTelegramRoute: WithmenuAccountConnectTelegramRoute,
  WithmenuAccountTokenRoute: WithmenuAccountTokenRoute,
  WithmenuAccountIndexRoute: WithmenuAccountIndexRoute,
};

const WithmenuAccountRouteRouteWithChildren =
  WithmenuAccountRouteRoute._addFileChildren(WithmenuAccountRouteRouteChildren);

interface WithmenuRouteRouteChildren {
  WithmenuAccountRouteRoute: typeof WithmenuAccountRouteRouteWithChildren;
  WithmenuCalendarRoute: typeof WithmenuCalendarRoute;
  WithmenuDashboardRoute: typeof WithmenuDashboardRoute;
  WithmenuDormsRoute: typeof WithmenuDormsRoute;
  WithmenuExtensionRoute: typeof WithmenuExtensionRoute;
  WithmenuMapsRoute: typeof WithmenuMapsRoute;
  WithmenuMenuRoute: typeof WithmenuMenuRoute;
  WithmenuPrintersRoute: typeof WithmenuPrintersRoute;
  WithmenuScholarshipRoute: typeof WithmenuScholarshipRoute;
  WithmenuSearchRoute: typeof WithmenuSearchRoute;
  WithmenuSportRoute: typeof WithmenuSportRoute;
  WithmenuMusicRoomInstructionsRoute: typeof WithmenuMusicRoomInstructionsRoute;
  WithmenuRoomBookingListRoute: typeof WithmenuRoomBookingListRoute;
  WithmenuRoomBookingRulesRoute: typeof WithmenuRoomBookingRulesRoute;
  WithmenuScheduleCategoryRoute: typeof WithmenuScheduleCategoryRoute;
  WithmenuMusicRoomIndexRoute: typeof WithmenuMusicRoomIndexRoute;
  WithmenuRoomBookingIndexRoute: typeof WithmenuRoomBookingIndexRoute;
  WithmenuScheduleIndexRoute: typeof WithmenuScheduleIndexRoute;
  WithmenuScheduleEventGroupsAliasRoute: typeof WithmenuScheduleEventGroupsAliasRoute;
}

const WithmenuRouteRouteChildren: WithmenuRouteRouteChildren = {
  WithmenuAccountRouteRoute: WithmenuAccountRouteRouteWithChildren,
  WithmenuCalendarRoute: WithmenuCalendarRoute,
  WithmenuDashboardRoute: WithmenuDashboardRoute,
  WithmenuDormsRoute: WithmenuDormsRoute,
  WithmenuExtensionRoute: WithmenuExtensionRoute,
  WithmenuMapsRoute: WithmenuMapsRoute,
  WithmenuMenuRoute: WithmenuMenuRoute,
  WithmenuPrintersRoute: WithmenuPrintersRoute,
  WithmenuScholarshipRoute: WithmenuScholarshipRoute,
  WithmenuSearchRoute: WithmenuSearchRoute,
  WithmenuSportRoute: WithmenuSportRoute,
  WithmenuMusicRoomInstructionsRoute: WithmenuMusicRoomInstructionsRoute,
  WithmenuRoomBookingListRoute: WithmenuRoomBookingListRoute,
  WithmenuRoomBookingRulesRoute: WithmenuRoomBookingRulesRoute,
  WithmenuScheduleCategoryRoute: WithmenuScheduleCategoryRoute,
  WithmenuMusicRoomIndexRoute: WithmenuMusicRoomIndexRoute,
  WithmenuRoomBookingIndexRoute: WithmenuRoomBookingIndexRoute,
  WithmenuScheduleIndexRoute: WithmenuScheduleIndexRoute,
  WithmenuScheduleEventGroupsAliasRoute: WithmenuScheduleEventGroupsAliasRoute,
};

const WithmenuRouteRouteWithChildren = WithmenuRouteRoute._addFileChildren(
  WithmenuRouteRouteChildren,
);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "": typeof WithmenuRouteRouteWithChildren;
  "/forms": typeof FormsRoute;
  "/account": typeof WithmenuAccountRouteRouteWithChildren;
  "/calendar": typeof WithmenuCalendarRoute;
  "/dashboard": typeof WithmenuDashboardRoute;
  "/dorms": typeof WithmenuDormsRoute;
  "/extension": typeof WithmenuExtensionRoute;
  "/maps": typeof WithmenuMapsRoute;
  "/menu": typeof WithmenuMenuRoute;
  "/printers": typeof WithmenuPrintersRoute;
  "/scholarship": typeof WithmenuScholarshipRoute;
  "/search": typeof WithmenuSearchRoute;
  "/sport": typeof WithmenuSportRoute;
  "/account/connect-telegram": typeof WithmenuAccountConnectTelegramRoute;
  "/account/token": typeof WithmenuAccountTokenRoute;
  "/music-room/instructions": typeof WithmenuMusicRoomInstructionsRoute;
  "/room-booking/list": typeof WithmenuRoomBookingListRoute;
  "/room-booking/rules": typeof WithmenuRoomBookingRulesRoute;
  "/schedule/$category": typeof WithmenuScheduleCategoryRoute;
  "/account/": typeof WithmenuAccountIndexRoute;
  "/music-room": typeof WithmenuMusicRoomIndexRoute;
  "/room-booking": typeof WithmenuRoomBookingIndexRoute;
  "/schedule": typeof WithmenuScheduleIndexRoute;
  "/schedule/event-groups/$alias": typeof WithmenuScheduleEventGroupsAliasRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "": typeof WithmenuRouteRouteWithChildren;
  "/forms": typeof FormsRoute;
  "/calendar": typeof WithmenuCalendarRoute;
  "/dashboard": typeof WithmenuDashboardRoute;
  "/dorms": typeof WithmenuDormsRoute;
  "/extension": typeof WithmenuExtensionRoute;
  "/maps": typeof WithmenuMapsRoute;
  "/menu": typeof WithmenuMenuRoute;
  "/printers": typeof WithmenuPrintersRoute;
  "/scholarship": typeof WithmenuScholarshipRoute;
  "/search": typeof WithmenuSearchRoute;
  "/sport": typeof WithmenuSportRoute;
  "/account/connect-telegram": typeof WithmenuAccountConnectTelegramRoute;
  "/account/token": typeof WithmenuAccountTokenRoute;
  "/music-room/instructions": typeof WithmenuMusicRoomInstructionsRoute;
  "/room-booking/list": typeof WithmenuRoomBookingListRoute;
  "/room-booking/rules": typeof WithmenuRoomBookingRulesRoute;
  "/schedule/$category": typeof WithmenuScheduleCategoryRoute;
  "/account": typeof WithmenuAccountIndexRoute;
  "/music-room": typeof WithmenuMusicRoomIndexRoute;
  "/room-booking": typeof WithmenuRoomBookingIndexRoute;
  "/schedule": typeof WithmenuScheduleIndexRoute;
  "/schedule/event-groups/$alias": typeof WithmenuScheduleEventGroupsAliasRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/_with_menu": typeof WithmenuRouteRouteWithChildren;
  "/forms": typeof FormsRoute;
  "/_with_menu/account": typeof WithmenuAccountRouteRouteWithChildren;
  "/_with_menu/calendar": typeof WithmenuCalendarRoute;
  "/_with_menu/dashboard": typeof WithmenuDashboardRoute;
  "/_with_menu/dorms": typeof WithmenuDormsRoute;
  "/_with_menu/extension": typeof WithmenuExtensionRoute;
  "/_with_menu/maps": typeof WithmenuMapsRoute;
  "/_with_menu/menu": typeof WithmenuMenuRoute;
  "/_with_menu/printers": typeof WithmenuPrintersRoute;
  "/_with_menu/scholarship": typeof WithmenuScholarshipRoute;
  "/_with_menu/search": typeof WithmenuSearchRoute;
  "/_with_menu/sport": typeof WithmenuSportRoute;
  "/_with_menu/account/connect-telegram": typeof WithmenuAccountConnectTelegramRoute;
  "/_with_menu/account/token": typeof WithmenuAccountTokenRoute;
  "/_with_menu/music-room/instructions": typeof WithmenuMusicRoomInstructionsRoute;
  "/_with_menu/room-booking/list": typeof WithmenuRoomBookingListRoute;
  "/_with_menu/room-booking/rules": typeof WithmenuRoomBookingRulesRoute;
  "/_with_menu/schedule/$category": typeof WithmenuScheduleCategoryRoute;
  "/_with_menu/account/": typeof WithmenuAccountIndexRoute;
  "/_with_menu/music-room/": typeof WithmenuMusicRoomIndexRoute;
  "/_with_menu/room-booking/": typeof WithmenuRoomBookingIndexRoute;
  "/_with_menu/schedule/": typeof WithmenuScheduleIndexRoute;
  "/_with_menu/schedule/event-groups/$alias": typeof WithmenuScheduleEventGroupsAliasRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | ""
    | "/forms"
    | "/account"
    | "/calendar"
    | "/dashboard"
    | "/dorms"
    | "/extension"
    | "/maps"
    | "/menu"
    | "/printers"
    | "/scholarship"
    | "/search"
    | "/sport"
    | "/account/connect-telegram"
    | "/account/token"
    | "/music-room/instructions"
    | "/room-booking/list"
    | "/room-booking/rules"
    | "/schedule/$category"
    | "/account/"
    | "/music-room"
    | "/room-booking"
    | "/schedule"
    | "/schedule/event-groups/$alias";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | ""
    | "/forms"
    | "/calendar"
    | "/dashboard"
    | "/dorms"
    | "/extension"
    | "/maps"
    | "/menu"
    | "/printers"
    | "/scholarship"
    | "/search"
    | "/sport"
    | "/account/connect-telegram"
    | "/account/token"
    | "/music-room/instructions"
    | "/room-booking/list"
    | "/room-booking/rules"
    | "/schedule/$category"
    | "/account"
    | "/music-room"
    | "/room-booking"
    | "/schedule"
    | "/schedule/event-groups/$alias";
  id:
    | "__root__"
    | "/"
    | "/_with_menu"
    | "/forms"
    | "/_with_menu/account"
    | "/_with_menu/calendar"
    | "/_with_menu/dashboard"
    | "/_with_menu/dorms"
    | "/_with_menu/extension"
    | "/_with_menu/maps"
    | "/_with_menu/menu"
    | "/_with_menu/printers"
    | "/_with_menu/scholarship"
    | "/_with_menu/search"
    | "/_with_menu/sport"
    | "/_with_menu/account/connect-telegram"
    | "/_with_menu/account/token"
    | "/_with_menu/music-room/instructions"
    | "/_with_menu/room-booking/list"
    | "/_with_menu/room-booking/rules"
    | "/_with_menu/schedule/$category"
    | "/_with_menu/account/"
    | "/_with_menu/music-room/"
    | "/_with_menu/room-booking/"
    | "/_with_menu/schedule/"
    | "/_with_menu/schedule/event-groups/$alias";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  WithmenuRouteRoute: typeof WithmenuRouteRouteWithChildren;
  FormsRoute: typeof FormsRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WithmenuRouteRoute: WithmenuRouteRouteWithChildren,
  FormsRoute: FormsRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_with_menu",
        "/forms"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_with_menu": {
      "filePath": "_with_menu/route.tsx",
      "children": [
        "/_with_menu/account",
        "/_with_menu/calendar",
        "/_with_menu/dashboard",
        "/_with_menu/dorms",
        "/_with_menu/extension",
        "/_with_menu/maps",
        "/_with_menu/menu",
        "/_with_menu/printers",
        "/_with_menu/scholarship",
        "/_with_menu/search",
        "/_with_menu/sport",
        "/_with_menu/music-room/instructions",
        "/_with_menu/room-booking/list",
        "/_with_menu/room-booking/rules",
        "/_with_menu/schedule/$category",
        "/_with_menu/music-room/",
        "/_with_menu/room-booking/",
        "/_with_menu/schedule/",
        "/_with_menu/schedule/event-groups/$alias"
      ]
    },
    "/forms": {
      "filePath": "forms.tsx"
    },
    "/_with_menu/account": {
      "filePath": "_with_menu/account/route.tsx",
      "parent": "/_with_menu",
      "children": [
        "/_with_menu/account/connect-telegram",
        "/_with_menu/account/token",
        "/_with_menu/account/"
      ]
    },
    "/_with_menu/calendar": {
      "filePath": "_with_menu/calendar.tsx",
      "parent": "/_with_menu"
    },
    "/_with_menu/dashboard": {
      "filePath": "_with_menu/dashboard.tsx",
      "parent": "/_with_menu"
    },
    "/_with_menu/dorms": {
      "filePath": "_with_menu/dorms.tsx",
      "parent": "/_with_menu"
    },
    "/_with_menu/extension": {
      "filePath": "_with_menu/extension.tsx",
      "parent": "/_with_menu"
    },
    "/_with_menu/maps": {
      "filePath": "_with_menu/maps.tsx",
      "parent": "/_with_menu"
    },
    "/_with_menu/menu": {
      "filePath": "_with_menu/menu.tsx",
      "parent": "/_with_menu"
    },
    "/_with_menu/printers": {
      "filePath": "_with_menu/printers.tsx",
      "parent": "/_with_menu"
    },
    "/_with_menu/scholarship": {
      "filePath": "_with_menu/scholarship.tsx",
      "parent": "/_with_menu"
    },
    "/_with_menu/search": {
      "filePath": "_with_menu/search.tsx",
      "parent": "/_with_menu"
    },
    "/_with_menu/sport": {
      "filePath": "_with_menu/sport.tsx",
      "parent": "/_with_menu"
    },
    "/_with_menu/account/connect-telegram": {
      "filePath": "_with_menu/account/connect-telegram.tsx",
      "parent": "/_with_menu/account"
    },
    "/_with_menu/account/token": {
      "filePath": "_with_menu/account/token.tsx",
      "parent": "/_with_menu/account"
    },
    "/_with_menu/music-room/instructions": {
      "filePath": "_with_menu/music-room.instructions.tsx",
      "parent": "/_with_menu"
    },
    "/_with_menu/room-booking/list": {
      "filePath": "_with_menu/room-booking/list.tsx",
      "parent": "/_with_menu"
    },
    "/_with_menu/room-booking/rules": {
      "filePath": "_with_menu/room-booking/rules.tsx",
      "parent": "/_with_menu"
    },
    "/_with_menu/schedule/$category": {
      "filePath": "_with_menu/schedule/$category.tsx",
      "parent": "/_with_menu"
    },
    "/_with_menu/account/": {
      "filePath": "_with_menu/account/index.tsx",
      "parent": "/_with_menu/account"
    },
    "/_with_menu/music-room/": {
      "filePath": "_with_menu/music-room.index.tsx",
      "parent": "/_with_menu"
    },
    "/_with_menu/room-booking/": {
      "filePath": "_with_menu/room-booking/index.tsx",
      "parent": "/_with_menu"
    },
    "/_with_menu/schedule/": {
      "filePath": "_with_menu/schedule/index.tsx",
      "parent": "/_with_menu"
    },
    "/_with_menu/schedule/event-groups/$alias": {
      "filePath": "_with_menu/schedule/event-groups.$alias.tsx",
      "parent": "/_with_menu"
    }
  }
}
ROUTE_MANIFEST_END */
